---
title: "Pilot study Aperol: questionnaire data"
author: "Mandy Klatt, Gregor Kachel and Anne Deiglmayr"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### HOW TO PREPARE DATA IN EXCEL ###
# use filter to select only lines with an ID in it 
# (i.e. exclude all empty lines or lines with na, ?, x, etc)
# select all columns except the columns for comments
# copy/paste into a new spreadsheet
# click "save as" and choose file type "tab-delimited-text"
####################################

# load tab delimited text file into R; 
# file should be in a subfolder named "data" for the script to select it
raw.data<-read.table("./data/questionnaire_data_080121.txt",sep="\t", header=T) 


# loading packages
# if a package is not installed on the current machine, it will install it
if (!require(tidyverse)) install.packages('tidyverse'); library(tidyverse)

# suppress "summarize" info. 
# if this line is committed, each table using the summarize function will be accompanied with a warning from the console
options(dplyr.summarise.inform = FALSE)

# # change data structure: everything is turned into factors except for 
# main.data <- raw.data %>%
#   filter(what == "data"& valid == 1)  %>%
#   mutate(across(!correct&!agem&!aged, as.factor),
#          correct = as.integer(correct))

view (raw.data)

```


### Plotting questionnaire data


```{r plot classroom management boxplot by groups, echo = FALSE}

### classroom management

# filter by parameter variable, i.e. create a subset for each group (expert/novice/experimenter)
km.data <- raw.data %>% filter(item == "Klassenmanagement")

view (raw.data)
class(raw.data$value)

# value sometimes contained text before filtering, we have to convert the numbers to numeric
km.data <- km.data %>%  mutate(value = as.numeric(as.character(factor(value))))


# create  mean, min, max, sd of classroom management
meankm <- mean(km.data$value)
minkm <- min(km.data$value)
maxkm <- max(km.data$value)
sdkm <- sd(km.data$value)
Nkm<-length(unique(km.data$ID))


# # filter by parametervariable, i.e. create a subset for the individual lecturer
# ind.km.data <- km.data %>% filter(Dozierende == params$Dozierende)
# # erstelle Mittelwert, min, max, sd for individual lecturer
# ind.meankm <- mean(ind.km.data$value)
# ind.minkm <- min(ind.km.data$value)
# ind.maxkm <- max(ind.km.data$value)
# ind.sdkm <- sd(ind.km.data$value)
# ind.Nkm<-length(unique(ind.km.data$ID))
```
