% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  english,
  man,floatsintext]{apa6}
\usepackage{lmodern}
\usepackage{amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
  \usepackage{amssymb}
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Through the eyes of the teacher},
  pdfauthor={Mandy Klatt1, Dr.~Gregor Kachel1, 2, Dr.~Christin Lotz1, \& Prof.~Dr.~Anne Deiglmayr1},
  pdflang={en-EN},
  pdfkeywords={Professional Vision, Expert-Novice-Paradigm, Eye-Tracking},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
% Manuscript styling
\usepackage{upgreek}
\captionsetup{font=singlespacing,justification=justified}

% Table formatting
\usepackage{longtable}
\usepackage{lscape}
% \usepackage[counterclockwise]{rotating}   % Landscape page setup for large tables
\usepackage{multirow}		% Table styling
\usepackage{tabularx}		% Control Column width
\usepackage[flushleft]{threeparttable}	% Allows for three part tables with a specified notes section
\usepackage{threeparttablex}            % Lets threeparttable work with longtable

% Create new environments so endfloat can handle them
% \newenvironment{ltable}
%   {\begin{landscape}\begin{center}\begin{threeparttable}}
%   {\end{threeparttable}\end{center}\end{landscape}}
\newenvironment{lltable}{\begin{landscape}\begin{center}\begin{ThreePartTable}}{\end{ThreePartTable}\end{center}\end{landscape}}

% Enables adjusting longtable caption width to table width
% Solution found at http://golatex.de/longtable-mit-caption-so-breit-wie-die-tabelle-t15767.html
\makeatletter
\newcommand\LastLTentrywidth{1em}
\newlength\longtablewidth
\setlength{\longtablewidth}{1in}
\newcommand{\getlongtablewidth}{\begingroup \ifcsname LT@\roman{LT@tables}\endcsname \global\longtablewidth=0pt \renewcommand{\LT@entry}[2]{\global\advance\longtablewidth by ##2\relax\gdef\LastLTentrywidth{##2}}\@nameuse{LT@\roman{LT@tables}} \fi \endgroup}

% \setlength{\parindent}{0.5in}
% \setlength{\parskip}{0pt plus 0pt minus 0pt}

% \usepackage{etoolbox}
\makeatletter
\patchcmd{\HyOrg@maketitle}
  {\section{\normalfont\normalsize\abstractname}}
  {\section*{\normalfont\normalsize\abstractname}}
  {}{\typeout{Failed to patch abstract.}}
\patchcmd{\HyOrg@maketitle}
  {\section{\protect\normalfont{\@title}}}
  {\section*{\protect\normalfont{\@title}}}
  {}{\typeout{Failed to patch title.}}
\makeatother
\shorttitle{Visual attention in teaching and learning processes}
\keywords{Professional Vision, Expert-Novice-Paradigm, Eye-Tracking\newline\indent Word count: 1949}
\usepackage{lineno}

\linenumbers
\usepackage{csquotes}
\ifxetex
  % Load polyglossia as late as possible: uses bidi with RTL langages (e.g. Hebrew, Arabic)
  \usepackage{polyglossia}
  \setmainlanguage[]{english}
\else
  \usepackage[shorthands=off,main=english]{babel}
\fi
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1 \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces\fi
  % set entry spacing
  \ifnum #2 > 0
  \setlength{\parskip}{#2\baselineskip}
  \fi
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\title{Through the eyes of the teacher}
\author{Mandy Klatt\textsuperscript{1}, Dr.~Gregor Kachel\textsuperscript{1, 2}, Dr.~Christin Lotz\textsuperscript{1}, \& Prof.~Dr.~Anne Deiglmayr\textsuperscript{1}}
\date{}


\authornote{

The study was carried out with the permission of the Ethics Committee of the University of Leipzig.

Correspondence concerning this article should be addressed to Mandy Klatt, Egelstraße 2a 04103 Leipzig. E-mail: \href{mailto:mandy.klatt@uni-leipzig.de}{\nolinkurl{mandy.klatt@uni-leipzig.de}}

}

\affiliation{\vspace{0.5cm}\textsuperscript{1} University of Leipzig\\\textsuperscript{2} MPI for Evolutionary Anthropology, Leipzig}

\abstract{
This document is a supplement to the paper and shows first graphs findings from the pilot study.
}



\begin{document}
\maketitle

\hypertarget{state-of-research}{%
\section{State of research}\label{state-of-research}}

Teaching and classroom management are multidimensional settings in which teachers have to respond immediately to events as they develop (Barnes, 2004). The different interests and abilities of students must be managed in a way that maximizes the active learning time of students and minimizes disruptions whilst teaching. Learning to develop such classroom management skills and to teach effectively is a complicated and complex process (Wolff, Jarodzka, \& Boshuizen, 2017).

During teaching, teachers must be able to select from a variety of visual and acoustic impressions to focus their attention on the essential and to distinguish between relevant and irrelevant events. This ability is called professional vision and is a key component of teacher expertise and successful teaching (Barth, 2017). Eye tracking technology has become a reliable means to study teachers' visual focus of attention (Bogert, 2016; Pouta, Lehtinen, \& Palonen, 2020; Wolff, Jarodzka, \& Boshuizen, 2017)

Educational research has repeatedly shown that there are differences between experienced and novice teachers in terms of perception and behavioral competencies (Barth, 2017; Bogert, 2016; Wolff, Jarodzka, \& Boshuizen, 2017). For example, experts direct their attention more often and more evenly to all students, whereas novices only direct their attention to some students. The frequency and duration of fixations as eye movement are decisive (Stuermer, Seidel, Mueller, Häusler, \& Cortina, 2017). Mobile eye-tracking technology has also shown that experienced teachers distribute their focus more efficiently to solve tasks (Jarodzka, Scheiter, Gerjets, \& Van Gog, 2010). Furthermore, in contrast to novices, experts are able to focus their attention on the entire class and guide the class while giving feedback to individual students and answering questions (Cortina, Miller, McKenzie, \& Epstein, 2015).

\hypertarget{research-questions}{%
\subsection{Research questions}\label{research-questions}}

The aim of the pilot study was to investigate whether there are differences in how expert and novice teachers manage scripted classroom disruptions. The disruptions were experimentally varied using a previously written script. Thus, our aim was to find out whether differences in the allocation of attention between expertise groups can be detected in this controlled context.

In order to answer this question, the hypothesis was formulated that teachers with more professional experience not only notice more disruptions but also notice them faster. In the hypothesis, therefore, it is necessary to check what has already been shown in the research literature: In complex teaching situations, experts have a more structured and elaborate professional knowledge than novices in order to perceive and interpret relevant events and to act appropriately (Berliner, 2001; Lachner, Jarodzka, \& Nückles, 2016).

\hypertarget{methods}{%
\section{Methods}\label{methods}}

We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study.

\hypertarget{participants}{%
\subsection{Participants}\label{participants}}

For the sample recruitment of the subjects (N = 48, experts n = 24, novices n = 24), schools in the city of Leipzig in Saxony were contacted. The institutions as well as the subjects were informed in detail about the aim and intention of the study in advance. Participation in the study was voluntary and only took place after written consent has been given.

\begin{table}[h]

\begin{center}
\begin{threeparttable}

\caption{\label{tab:demographicspilottable}Demographic Informationand and Teaching Experience}

\small{

\begin{tabular}{lllllllllll}
\toprule
group & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{Male} & \multicolumn{1}{c}{M age} & \multicolumn{1}{c}{Min age} & \multicolumn{1}{c}{Max age} & \multicolumn{1}{c}{SD age} & \multicolumn{1}{c}{M exp.} & \multicolumn{1}{c}{Min exp.} & \multicolumn{1}{c}{Max exp.} & \multicolumn{1}{c}{SD exp.}\\
\midrule
expert & 2 & 1 & 47.50 & 44 & 51 & 4.95 & 20.00 & 15.00 & 25.00 & 7.07\\
novice & 6 & 2 & 25.67 & 20 & 33 & 4.89 & 0.68 & 0.00 & 1.50 & 0.68\\
\bottomrule
\end{tabular}

}

\end{threeparttable}
\end{center}

\end{table}

The selection of the subjects was based on extreme groups, whereby professional experience is the crucial criterion for the selection of experts or novices. Novices were recruited as teachers who have been working in the teaching profession for no more than 3 years, whereas experts were considered to have professional experience of 10 years or more (Messner \& Reusser, 2000).

\hypertarget{procedure-data-collection}{%
\subsection{Procedure/ Data collection}\label{procedure-data-collection}}

\hypertarget{set-up}{%
\subsubsection{Set up}\label{set-up}}

For this study, scripted mini-lessons with n = 2 experts and n = 6 novices were recorded in the mobile Lab of the Empirical School and Classroom Research at the University of Leipzig. The subjects were divided into groups of four, so the study was conducted on two different sessions. All participants were asked to hold a 10-minute lesson. The duration of each appointment was approximately 2h: per group 10min briefing, 4 x 10min mini-lessons, 10min technical preparation and follow-up and 4x 10min transition points between the lessons and answering questionnaires.

One person from the group of 4 acted as a teacher, the other three subjects acted as the class. The subjects, who represented the class, were given behavioral instructions in a pre-written script to simulate typical events and disruptions in the classroom (e.g.~putting their heads on the table, chatting, looking at their mobile phones, etc.).

The lesson disruptions were displayed as instructions during the lesson for all ``students'' but not the teacher. In order to avoid learning effects, the disruptions in each lesson were distributed pseudo-randomly over the short teaching phase. In addition, the order of the data collection was taken into account in the analyses and variance caused by order was controlled.



\begin{figure}

{\centering \includegraphics{./pictures/datacollection} 

}

\caption{Example for set up during a mini-lesson}\label{fig:datacollection}
\end{figure}

\hypertarget{questionnaire-data}{%
\subsubsection{Questionnaire data}\label{questionnaire-data}}

After each mini-lesson, the subjects answered items on the teaching quality using a validated questionnaire ((Helmke et al. (2014))) and scales on the teacher's presence behavior. An external observer also completed the questionnaire. In addition, the teacher was asked to give a self-assessment on his/her classroom management by completing the questionnaire.

\hypertarget{behavioral-data}{%
\subsubsection{Behavioral data}\label{behavioral-data}}

The speech, sounds and voices were recorded with an audio recorder installed in the middle of the Lab. Movements, facial expressions and gestures of the subjects were recorded by four cameras from different angles. One camera was installed to film the class from the side. Two more cameras were installed on the blackboard and at the end of the Lab to film the teacher and class from the front and back. Furthermore, the fourth camera was installed in such a way that only facial expressions and gestures of the teacher were recorded, which enables a semi-automated analysis of the movement sequences.

\hypertarget{eyetracking-data}{%
\subsubsection{Eyetracking data}\label{eyetracking-data}}

A binocular Tobii Pro Glasses 2 eye-tracker consisting of a wearable head unit and a recording unit was used to record the eye movements of all 8 participants. The head unit is a measuring device with different sensitive sensors. A high-definition scene camera captures a full HD video and an integrated microphone records the surrounding sounds. Infrared light illuminators support the eye tracking sensors which record the eye orientation. The videos were recorded with a sampling rate of 50 Hz and a video resolution with 1920 x 1080 at 25 frames per second. The scene camera has a field of view of 90 deg. in 16:9 format (82 deg. horizontal and 52 deg. vertical) and has a frame dimension of 179 x 159 x 57mm (width x depth x height). The Tobii Pro Glasses Controller software was used to record and calibrate the eye movements.

\hypertarget{coding-data-preparation-reliability}{%
\subsection{Coding/ Data preparation/ Reliability}\label{coding-data-preparation-reliability}}

\hypertarget{questionnaire-data-1}{%
\subsubsection{Questionnaire Data}\label{questionnaire-data-1}}

The evaluation after each mini-lesson was conducted using paper questionnaires. Time needed to complete the questionnaire was about 5 minutes.
The scales on the quality of teaching are a validated questionnaire (Helmke et al. (2014)). Whereas the scales on the teacher's presence behavior were derived from the research literature (Brophy (1986); Kiel, Frey, Weiß, and Weiss (2013); Kounin (2006); Marzano (2007); Nolting (2012)) and were used in the pilot for the first time.

The following scales were assessed:

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  Classroom management
\item
  Positive climate and motivation
\item
  Clarity and structuredness
\item
  Activation and support
\item
  Presence: posture/gaze
\item
  Presence: voice
\item
  Presence: verbal and non-verbal intervention
\item
  Natural behaviour
\end{enumerate}

The table at the end of the manuscript provides an overview over the mean, the range and standard deviation of all scales.

\begin{table}[h]

\begin{center}
\begin{threeparttable}

\caption{\label{tab:table all scales}Mean values of all scales}

\small{

\begin{tabular}{llllll}
\toprule
group & \multicolumn{1}{c}{scale} & \multicolumn{1}{c}{M scale} & \multicolumn{1}{c}{min scale} & \multicolumn{1}{c}{max sclae} & \multicolumn{1}{c}{SD scale}\\
\midrule
expert & Activation and support & 3.33 & 2.00 & 4.00 & 0.80\\
 & Clarity and structuredness & 3.70 & 1.00 & 4.00 & 0.73\\
 & Classroom management & 3.23 & 1.00 & 4.00 & 0.90\\
 & Natural behaviour & 3.57 & 2.00 & 4.00 & 0.63\\
 & Positive climate and motivation & 3.60 & 2.00 & 4.00 & 0.62\\
 & Presence: posture/gaze & 3.29 & 1.00 & 4.00 & 0.92\\
 & Presence: verbal and non-verbal intervention & 3.07 & 2.00 & 4.00 & 0.78\\
 & Presence: voice & 3.57 & 2.00 & 4.00 & 0.63\\
novice & Activation and support & 2.23 & 0.00 & 4.00 & 1.39\\
 & Clarity and structuredness & 3.35 & 1.00 & 4.00 & 0.76\\
 & Classroom management & 2.82 & 1.00 & 4.00 & 0.90\\
 & Natural behaviour & 3.13 & 2.00 & 4.00 & 0.71\\
 & Positive climate and motivation & 3.11 & 0.00 & 4.00 & 0.90\\
 & Presence: posture/gaze & 2.95 & 0.00 & 4.00 & 0.95\\
 & Presence: verbal and non-verbal intervention & 2.88 & 1.00 & 4.00 & 0.97\\
 & Presence: voice & 3.30 & 2.00 & 4.00 & 0.74\\
\bottomrule
\end{tabular}

}

\end{threeparttable}
\end{center}

\end{table}

\newpage

The individual items of a scale are further represented in graphs.

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  Classroom management
  \includegraphics{paper_1_supplement_files/figure-latex/classroom management line plots-1.pdf}
  \newpage
\item
  Positive climate and motivation
  \includegraphics{paper_1_supplement_files/figure-latex/Positive climate and motivation line plots-1.pdf}
  \newpage
\item
  Clarity and structuredness
  \includegraphics{paper_1_supplement_files/figure-latex/Clarity and structuredness line plots-1.pdf}
  \newpage
\item
  Activation and support
  \includegraphics{paper_1_supplement_files/figure-latex/Activation and support line plots-1.pdf}
  \newpage
\end{enumerate}



\begin{figure}

{\centering \includegraphics{./pictures/presenceposturegaze} 

}

\caption{(5) Presence: posture/gaze}\label{fig:presenceposturegaze}
\end{figure}

\newpage



\begin{figure}

{\centering \includegraphics{./pictures/presencevoice} 

}

\caption{(6) Presence: voice}\label{fig:presencevoice}
\end{figure}
\newpage



\begin{figure}

{\centering \includegraphics{./pictures/presenceverbalnonverbalintervention} 

}

\caption{(7) Presence: verbal and non-verbal intervention}\label{fig:presenceverbalnonverbalintervention}
\end{figure}
\newpage

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\setcounter{enumi}{7}
\tightlist
\item
  Natural behaviour
  \includegraphics{paper_1_supplement_files/figure-latex/Natural behaviour line plots-1.pdf}
  \newpage
  In addition, we plotted all scales. Graph provides boxplots and individual data for experts and novices.
\end{enumerate}

\includegraphics{paper_1_supplement_files/figure-latex/boxplot scales-1.pdf}

\newpage

\hypertarget{behavioral-data-1}{%
\subsubsection{Behavioral Data}\label{behavioral-data-1}}

The recorded lessons were coded in a post-hoc procedure with the coding software MAXQDA by previously trained raters (Kuckartz and Rädiker (2019)). The following coding scheme was developed:

First, we coded the speaking time of the teacher and the students to compare all perspectives: coder, observer, students, teacher. The graph below shows the result of the coded speaking duration compared to the estimated speaking duration assessed with the questionnaire.

\begin{verbatim}
## 'data.frame':    325 obs. of  7 variables:
##  $ Dokumentgruppe  : chr  "kodiert von Anna" "kodiert von Anna" "kodiert von Anna" "kodiert von Anna" ...
##  $ Dokumentname    : chr  "Aperol_pilot_01_01_expert_D_cam4" "Aperol_pilot_01_01_expert_D_cam4" "Aperol_pilot_01_01_expert_D_cam4" "Aperol_pilot_01_01_expert_D_cam4" ...
##  $ Code            : chr  "Phase\\lesson begin" "speaking time\\teacher" "speaking time\\teacher" "speaking time\\student" ...
##  $ Anfang          : chr  "0:00:44,0" "0:00:44,3" "0:00:49,2" "0:00:51,0" ...
##  $ Ende            : chr  "0:00:44,2" "0:00:47,2" "0:00:50,7" "0:00:52,7" ...
##  $ Fläche          : chr  "00:00:00,2" "00:00:02,8" "00:00:01,4" "00:00:01,6" ...
##  $ Abdeckungsgrad..: num  0.04 0.39 0.19 0.22 0.12 0.13 0.19 1.58 7.3 0.54 ...
\end{verbatim}

\begin{verbatim}
##        Dokumentgruppe Dokumentname  Code Anfang  Ende Fläche Abdeckungsgrad..
##   [1,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [2,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [3,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [4,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [5,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [6,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [7,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [8,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [9,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [10,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [11,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [12,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [13,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [14,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [15,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [16,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [17,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [18,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [19,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [20,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [21,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [22,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [23,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [24,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [25,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [26,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [27,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [28,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [29,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [30,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [31,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [32,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [33,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [34,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [35,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [36,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [37,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [38,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [39,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [40,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [41,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [42,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [43,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [44,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [45,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [46,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [47,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [48,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [49,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [50,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [51,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [52,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [53,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [54,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [55,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [56,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [57,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [58,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [59,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [60,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [61,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [62,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [63,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [64,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [65,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [66,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [67,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [68,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [69,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [70,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [71,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [72,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [73,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [74,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [75,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [76,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [77,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [78,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [79,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [80,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [81,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [82,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [83,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [84,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [85,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [86,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [87,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [88,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [89,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [90,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [91,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [92,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [93,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [94,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [95,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [96,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [97,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [98,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [99,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [100,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [101,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [102,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [103,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [104,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [105,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [106,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [107,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [108,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [109,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [110,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [111,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [112,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [113,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [114,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [115,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [116,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [117,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [118,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [119,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [120,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [121,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [122,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [123,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [124,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [125,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [126,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [127,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [128,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [129,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [130,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [131,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [132,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [133,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [134,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [135,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [136,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [137,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [138,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [139,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [140,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [141,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [142,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [143,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [144,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [145,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [146,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [147,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [148,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [149,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [150,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [151,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [152,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [153,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [154,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [155,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [156,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [157,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [158,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [159,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [160,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [161,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [162,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [163,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [164,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [165,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [166,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [167,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [168,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [169,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [170,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [171,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [172,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [173,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [174,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [175,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [176,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [177,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [178,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [179,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [180,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [181,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [182,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [183,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [184,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [185,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [186,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [187,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [188,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [189,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [190,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [191,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [192,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [193,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [194,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [195,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [196,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [197,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [198,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [199,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [200,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [201,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [202,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [203,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [204,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [205,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [206,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [207,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [208,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [209,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [210,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [211,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [212,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [213,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [214,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [215,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [216,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [217,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [218,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [219,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [220,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [221,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [222,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [223,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [224,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [225,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [226,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [227,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [228,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [229,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [230,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [231,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [232,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [233,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [234,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [235,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [236,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [237,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [238,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [239,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [240,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [241,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [242,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [243,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [244,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [245,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [246,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [247,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [248,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [249,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [250,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [251,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [252,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [253,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [254,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [255,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [256,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [257,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [258,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [259,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [260,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [261,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [262,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [263,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [264,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [265,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [266,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [267,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [268,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [269,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [270,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [271,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [272,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [273,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [274,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [275,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [276,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [277,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [278,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [279,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [280,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [281,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [282,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [283,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [284,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [285,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [286,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [287,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [288,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [289,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [290,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [291,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [292,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [293,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [294,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [295,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [296,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [297,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [298,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [299,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [300,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [301,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [302,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [303,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [304,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [305,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [306,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [307,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [308,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [309,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [310,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [311,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [312,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [313,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [314,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [315,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [316,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [317,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [318,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [319,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [320,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [321,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [322,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [323,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [324,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [325,]          FALSE        FALSE FALSE  FALSE FALSE  FALSE            FALSE
\end{verbatim}

\begin{verbatim}
## integer(0)
\end{verbatim}

\begin{verbatim}
##        Dokumentname  Code Anfang  Ende Fläche Abdeckungsgrad..
##   [1,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [2,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [3,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [4,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [5,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [6,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [7,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [8,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [9,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [10,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [11,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [12,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [13,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [14,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [15,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [16,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [17,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [18,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [19,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [20,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [21,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [22,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [23,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [24,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [25,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [26,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [27,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [28,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [29,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [30,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [31,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [32,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [33,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [34,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [35,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [36,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [37,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [38,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [39,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [40,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [41,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [42,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [43,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [44,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [45,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [46,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [47,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [48,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [49,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [50,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [51,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [52,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [53,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [54,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [55,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [56,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [57,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [58,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [59,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [60,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [61,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [62,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [63,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [64,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [65,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [66,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [67,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [68,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [69,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [70,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [71,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [72,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [73,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [74,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [75,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [76,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [77,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [78,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [79,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [80,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [81,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [82,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [83,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [84,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [85,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [86,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [87,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [88,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [89,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [90,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [91,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [92,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [93,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [94,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [95,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [96,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [97,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [98,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [99,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [100,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [101,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [102,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [103,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [104,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [105,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [106,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [107,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [108,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [109,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [110,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [111,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [112,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [113,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [114,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [115,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [116,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [117,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [118,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [119,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [120,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [121,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [122,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [123,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [124,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [125,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [126,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [127,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [128,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [129,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [130,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [131,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [132,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [133,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [134,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [135,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [136,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [137,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [138,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [139,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [140,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [141,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [142,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [143,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [144,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [145,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [146,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [147,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [148,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [149,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [150,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [151,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [152,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [153,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [154,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [155,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [156,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [157,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [158,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [159,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [160,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [161,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [162,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [163,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [164,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [165,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [166,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [167,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [168,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [169,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [170,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [171,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [172,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [173,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [174,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [175,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [176,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [177,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [178,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [179,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [180,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [181,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [182,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [183,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [184,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [185,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [186,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [187,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [188,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [189,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [190,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [191,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [192,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [193,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [194,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [195,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [196,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [197,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [198,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [199,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [200,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [201,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [202,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [203,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [204,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [205,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [206,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [207,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [208,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [209,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [210,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [211,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [212,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [213,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [214,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [215,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [216,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [217,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [218,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [219,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [220,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [221,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [222,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [223,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [224,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [225,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [226,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [227,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [228,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [229,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [230,]        FALSE FALSE  FALSE FALSE  FALSE            FALSE
\end{verbatim}

\begin{verbatim}
## integer(0)
\end{verbatim}

\begin{verbatim}
## 'data.frame':    179 obs. of  5 variables:
##  $ Code            : chr  "Phase\\lesson begin" "speaking time\\teachter" "Phase\\teachers lecture" "Phase\\single" ...
##  $ Anfang          : chr  "0:00:44,4" "0:00:44,4" "0:00:44,4" "0:01:20,8" ...
##  $ Ende            : chr  "0:00:44,6" "0:01:20,7" "0:01:20,7" "0:01:51,7" ...
##  $ Fläche          : chr  "00:00:00,1" "00:00:36,3" "00:00:36,3" "00:00:30,8" ...
##  $ Abdeckungsgrad..: num  0.03 5.15 5.15 4.37 0.04 0.96 0.62 0.02 0.04 0.16 ...
\end{verbatim}

\begin{verbatim}
##         Code Anfang  Ende Fläche Abdeckungsgrad..
##   [1,] FALSE  FALSE FALSE  FALSE            FALSE
##   [2,] FALSE  FALSE FALSE  FALSE            FALSE
##   [3,] FALSE  FALSE FALSE  FALSE            FALSE
##   [4,] FALSE  FALSE FALSE  FALSE            FALSE
##   [5,] FALSE  FALSE FALSE  FALSE            FALSE
##   [6,] FALSE  FALSE FALSE  FALSE            FALSE
##   [7,] FALSE  FALSE FALSE  FALSE            FALSE
##   [8,] FALSE  FALSE FALSE  FALSE            FALSE
##   [9,] FALSE  FALSE FALSE  FALSE            FALSE
##  [10,] FALSE  FALSE FALSE  FALSE            FALSE
##  [11,] FALSE  FALSE FALSE  FALSE            FALSE
##  [12,] FALSE  FALSE FALSE  FALSE            FALSE
##  [13,] FALSE  FALSE FALSE  FALSE            FALSE
##  [14,] FALSE  FALSE FALSE  FALSE            FALSE
##  [15,] FALSE  FALSE FALSE  FALSE            FALSE
##  [16,] FALSE  FALSE FALSE  FALSE            FALSE
##  [17,] FALSE  FALSE FALSE  FALSE            FALSE
##  [18,] FALSE  FALSE FALSE  FALSE            FALSE
##  [19,] FALSE  FALSE FALSE  FALSE            FALSE
##  [20,] FALSE  FALSE FALSE  FALSE            FALSE
##  [21,] FALSE  FALSE FALSE  FALSE            FALSE
##  [22,] FALSE  FALSE FALSE  FALSE            FALSE
##  [23,] FALSE  FALSE FALSE  FALSE            FALSE
##  [24,] FALSE  FALSE FALSE  FALSE            FALSE
##  [25,] FALSE  FALSE FALSE  FALSE            FALSE
##  [26,] FALSE  FALSE FALSE  FALSE            FALSE
##  [27,] FALSE  FALSE FALSE  FALSE            FALSE
##  [28,] FALSE  FALSE FALSE  FALSE            FALSE
##  [29,] FALSE  FALSE FALSE  FALSE            FALSE
##  [30,] FALSE  FALSE FALSE  FALSE            FALSE
##  [31,] FALSE  FALSE FALSE  FALSE            FALSE
##  [32,] FALSE  FALSE FALSE  FALSE            FALSE
##  [33,] FALSE  FALSE FALSE  FALSE            FALSE
##  [34,] FALSE  FALSE FALSE  FALSE            FALSE
##  [35,] FALSE  FALSE FALSE  FALSE            FALSE
##  [36,] FALSE  FALSE FALSE  FALSE            FALSE
##  [37,] FALSE  FALSE FALSE  FALSE            FALSE
##  [38,] FALSE  FALSE FALSE  FALSE            FALSE
##  [39,] FALSE  FALSE FALSE  FALSE            FALSE
##  [40,] FALSE  FALSE FALSE  FALSE            FALSE
##  [41,] FALSE  FALSE FALSE  FALSE            FALSE
##  [42,] FALSE  FALSE FALSE  FALSE            FALSE
##  [43,] FALSE  FALSE FALSE  FALSE            FALSE
##  [44,] FALSE  FALSE FALSE  FALSE            FALSE
##  [45,] FALSE  FALSE FALSE  FALSE            FALSE
##  [46,] FALSE  FALSE FALSE  FALSE            FALSE
##  [47,] FALSE  FALSE FALSE  FALSE            FALSE
##  [48,] FALSE  FALSE FALSE  FALSE            FALSE
##  [49,] FALSE  FALSE FALSE  FALSE            FALSE
##  [50,] FALSE  FALSE FALSE  FALSE            FALSE
##  [51,] FALSE  FALSE FALSE  FALSE            FALSE
##  [52,] FALSE  FALSE FALSE  FALSE            FALSE
##  [53,] FALSE  FALSE FALSE  FALSE            FALSE
##  [54,] FALSE  FALSE FALSE  FALSE            FALSE
##  [55,] FALSE  FALSE FALSE  FALSE            FALSE
##  [56,] FALSE  FALSE FALSE  FALSE            FALSE
##  [57,] FALSE  FALSE FALSE  FALSE            FALSE
##  [58,] FALSE  FALSE FALSE  FALSE            FALSE
##  [59,] FALSE  FALSE FALSE  FALSE            FALSE
##  [60,] FALSE  FALSE FALSE  FALSE            FALSE
##  [61,] FALSE  FALSE FALSE  FALSE            FALSE
##  [62,] FALSE  FALSE FALSE  FALSE            FALSE
##  [63,] FALSE  FALSE FALSE  FALSE            FALSE
##  [64,] FALSE  FALSE FALSE  FALSE            FALSE
##  [65,] FALSE  FALSE FALSE  FALSE            FALSE
##  [66,] FALSE  FALSE FALSE  FALSE            FALSE
##  [67,] FALSE  FALSE FALSE  FALSE            FALSE
##  [68,] FALSE  FALSE FALSE  FALSE            FALSE
##  [69,] FALSE  FALSE FALSE  FALSE            FALSE
##  [70,] FALSE  FALSE FALSE  FALSE            FALSE
##  [71,] FALSE  FALSE FALSE  FALSE            FALSE
##  [72,] FALSE  FALSE FALSE  FALSE            FALSE
##  [73,] FALSE  FALSE FALSE  FALSE            FALSE
##  [74,] FALSE  FALSE FALSE  FALSE            FALSE
##  [75,] FALSE  FALSE FALSE  FALSE            FALSE
##  [76,] FALSE  FALSE FALSE  FALSE            FALSE
##  [77,] FALSE  FALSE FALSE  FALSE            FALSE
##  [78,] FALSE  FALSE FALSE  FALSE            FALSE
##  [79,] FALSE  FALSE FALSE  FALSE            FALSE
##  [80,] FALSE  FALSE FALSE  FALSE            FALSE
##  [81,] FALSE  FALSE FALSE  FALSE            FALSE
##  [82,] FALSE  FALSE FALSE  FALSE            FALSE
##  [83,] FALSE  FALSE FALSE  FALSE            FALSE
##  [84,] FALSE  FALSE FALSE  FALSE            FALSE
##  [85,] FALSE  FALSE FALSE  FALSE            FALSE
##  [86,] FALSE  FALSE FALSE  FALSE            FALSE
##  [87,] FALSE  FALSE FALSE  FALSE            FALSE
##  [88,] FALSE  FALSE FALSE  FALSE            FALSE
##  [89,] FALSE  FALSE FALSE  FALSE            FALSE
##  [90,] FALSE  FALSE FALSE  FALSE            FALSE
##  [91,] FALSE  FALSE FALSE  FALSE            FALSE
##  [92,] FALSE  FALSE FALSE  FALSE            FALSE
##  [93,] FALSE  FALSE FALSE  FALSE            FALSE
##  [94,] FALSE  FALSE FALSE  FALSE            FALSE
##  [95,] FALSE  FALSE FALSE  FALSE            FALSE
##  [96,] FALSE  FALSE FALSE  FALSE            FALSE
##  [97,] FALSE  FALSE FALSE  FALSE            FALSE
##  [98,] FALSE  FALSE FALSE  FALSE            FALSE
##  [99,] FALSE  FALSE FALSE  FALSE            FALSE
## [100,] FALSE  FALSE FALSE  FALSE            FALSE
## [101,] FALSE  FALSE FALSE  FALSE            FALSE
## [102,] FALSE  FALSE FALSE  FALSE            FALSE
## [103,] FALSE  FALSE FALSE  FALSE            FALSE
## [104,] FALSE  FALSE FALSE  FALSE            FALSE
## [105,] FALSE  FALSE FALSE  FALSE            FALSE
## [106,] FALSE  FALSE FALSE  FALSE            FALSE
## [107,] FALSE  FALSE FALSE  FALSE            FALSE
## [108,] FALSE  FALSE FALSE  FALSE            FALSE
## [109,] FALSE  FALSE FALSE  FALSE            FALSE
## [110,] FALSE  FALSE FALSE  FALSE            FALSE
## [111,] FALSE  FALSE FALSE  FALSE            FALSE
## [112,] FALSE  FALSE FALSE  FALSE            FALSE
## [113,] FALSE  FALSE FALSE  FALSE            FALSE
## [114,] FALSE  FALSE FALSE  FALSE            FALSE
## [115,] FALSE  FALSE FALSE  FALSE            FALSE
## [116,] FALSE  FALSE FALSE  FALSE            FALSE
## [117,] FALSE  FALSE FALSE  FALSE            FALSE
## [118,] FALSE  FALSE FALSE  FALSE            FALSE
## [119,] FALSE  FALSE FALSE  FALSE            FALSE
## [120,] FALSE  FALSE FALSE  FALSE            FALSE
## [121,] FALSE  FALSE FALSE  FALSE            FALSE
## [122,] FALSE  FALSE FALSE  FALSE            FALSE
## [123,] FALSE  FALSE FALSE  FALSE            FALSE
## [124,] FALSE  FALSE FALSE  FALSE            FALSE
## [125,] FALSE  FALSE FALSE  FALSE            FALSE
## [126,] FALSE  FALSE FALSE  FALSE            FALSE
## [127,] FALSE  FALSE FALSE  FALSE            FALSE
## [128,] FALSE  FALSE FALSE  FALSE            FALSE
## [129,] FALSE  FALSE FALSE  FALSE            FALSE
## [130,] FALSE  FALSE FALSE  FALSE            FALSE
## [131,] FALSE  FALSE FALSE  FALSE            FALSE
## [132,] FALSE  FALSE FALSE  FALSE            FALSE
## [133,] FALSE  FALSE FALSE  FALSE            FALSE
## [134,] FALSE  FALSE FALSE  FALSE            FALSE
## [135,] FALSE  FALSE FALSE  FALSE            FALSE
## [136,] FALSE  FALSE FALSE  FALSE            FALSE
## [137,] FALSE  FALSE FALSE  FALSE            FALSE
## [138,] FALSE  FALSE FALSE  FALSE            FALSE
## [139,] FALSE  FALSE FALSE  FALSE            FALSE
## [140,] FALSE  FALSE FALSE  FALSE            FALSE
## [141,] FALSE  FALSE FALSE  FALSE            FALSE
## [142,] FALSE  FALSE FALSE  FALSE            FALSE
## [143,] FALSE  FALSE FALSE  FALSE            FALSE
## [144,] FALSE  FALSE FALSE  FALSE            FALSE
## [145,] FALSE  FALSE FALSE  FALSE            FALSE
## [146,] FALSE  FALSE FALSE  FALSE            FALSE
## [147,] FALSE  FALSE FALSE  FALSE            FALSE
## [148,] FALSE  FALSE FALSE  FALSE            FALSE
## [149,] FALSE  FALSE FALSE  FALSE            FALSE
## [150,] FALSE  FALSE FALSE  FALSE            FALSE
## [151,] FALSE  FALSE FALSE  FALSE            FALSE
## [152,] FALSE  FALSE FALSE  FALSE            FALSE
## [153,] FALSE  FALSE FALSE  FALSE            FALSE
## [154,] FALSE  FALSE FALSE  FALSE            FALSE
## [155,] FALSE  FALSE FALSE  FALSE            FALSE
## [156,] FALSE  FALSE FALSE  FALSE            FALSE
## [157,] FALSE  FALSE FALSE  FALSE            FALSE
## [158,] FALSE  FALSE FALSE  FALSE            FALSE
## [159,] FALSE  FALSE FALSE  FALSE            FALSE
## [160,] FALSE  FALSE FALSE  FALSE            FALSE
## [161,] FALSE  FALSE FALSE  FALSE            FALSE
## [162,] FALSE  FALSE FALSE  FALSE            FALSE
## [163,] FALSE  FALSE FALSE  FALSE            FALSE
## [164,] FALSE  FALSE FALSE  FALSE            FALSE
## [165,] FALSE  FALSE FALSE  FALSE            FALSE
## [166,] FALSE  FALSE FALSE  FALSE            FALSE
## [167,] FALSE  FALSE FALSE  FALSE            FALSE
## [168,] FALSE  FALSE FALSE  FALSE            FALSE
## [169,] FALSE  FALSE FALSE  FALSE            FALSE
## [170,] FALSE  FALSE FALSE  FALSE            FALSE
## [171,] FALSE  FALSE FALSE  FALSE            FALSE
## [172,] FALSE  FALSE FALSE  FALSE            FALSE
## [173,] FALSE  FALSE FALSE  FALSE            FALSE
## [174,] FALSE  FALSE FALSE  FALSE            FALSE
## [175,] FALSE  FALSE FALSE  FALSE            FALSE
## [176,] FALSE  FALSE FALSE  FALSE            FALSE
## [177,] FALSE  FALSE FALSE  FALSE            FALSE
## [178,] FALSE  FALSE FALSE  FALSE            FALSE
## [179,] FALSE  FALSE FALSE  FALSE            FALSE
\end{verbatim}

\begin{verbatim}
## integer(0)
\end{verbatim}

\begin{verbatim}
## 'data.frame':    190 obs. of  5 variables:
##  $ Code            : chr  "Phase\\lesson begin" "speaking time\\teachter" "speaking time\\student" "speaking time\\teachter" ...
##  $ Anfang          : chr  "0:00:56,9" "0:00:56,9" "0:01:00,7" "0:01:01,8" ...
##  $ Ende            : chr  "0:00:57,6" "0:01:01,0" "0:01:03,0" "0:01:03,0" ...
##  $ Fläche          : chr  "00:00:00,6" "00:00:04,0" "00:00:02,3" "00:00:01,1" ...
##  $ Abdeckungsgrad..: num  0.09 0.59 0.34 0.17 0.24 0.24 0.1 5.54 0.07 3.39 ...
\end{verbatim}

\begin{verbatim}
##         Code Anfang  Ende Fläche Abdeckungsgrad..
##   [1,] FALSE  FALSE FALSE  FALSE            FALSE
##   [2,] FALSE  FALSE FALSE  FALSE            FALSE
##   [3,] FALSE  FALSE FALSE  FALSE            FALSE
##   [4,] FALSE  FALSE FALSE  FALSE            FALSE
##   [5,] FALSE  FALSE FALSE  FALSE            FALSE
##   [6,] FALSE  FALSE FALSE  FALSE            FALSE
##   [7,] FALSE  FALSE FALSE  FALSE            FALSE
##   [8,] FALSE  FALSE FALSE  FALSE            FALSE
##   [9,] FALSE  FALSE FALSE  FALSE            FALSE
##  [10,] FALSE  FALSE FALSE  FALSE            FALSE
##  [11,] FALSE  FALSE FALSE  FALSE            FALSE
##  [12,] FALSE  FALSE FALSE  FALSE            FALSE
##  [13,] FALSE  FALSE FALSE  FALSE            FALSE
##  [14,] FALSE  FALSE FALSE  FALSE            FALSE
##  [15,] FALSE  FALSE FALSE  FALSE            FALSE
##  [16,] FALSE  FALSE FALSE  FALSE            FALSE
##  [17,] FALSE  FALSE FALSE  FALSE            FALSE
##  [18,] FALSE  FALSE FALSE  FALSE            FALSE
##  [19,] FALSE  FALSE FALSE  FALSE            FALSE
##  [20,] FALSE  FALSE FALSE  FALSE            FALSE
##  [21,] FALSE  FALSE FALSE  FALSE            FALSE
##  [22,] FALSE  FALSE FALSE  FALSE            FALSE
##  [23,] FALSE  FALSE FALSE  FALSE            FALSE
##  [24,] FALSE  FALSE FALSE  FALSE            FALSE
##  [25,] FALSE  FALSE FALSE  FALSE            FALSE
##  [26,] FALSE  FALSE FALSE  FALSE            FALSE
##  [27,] FALSE  FALSE FALSE  FALSE            FALSE
##  [28,] FALSE  FALSE FALSE  FALSE            FALSE
##  [29,] FALSE  FALSE FALSE  FALSE            FALSE
##  [30,] FALSE  FALSE FALSE  FALSE            FALSE
##  [31,] FALSE  FALSE FALSE  FALSE            FALSE
##  [32,] FALSE  FALSE FALSE  FALSE            FALSE
##  [33,] FALSE  FALSE FALSE  FALSE            FALSE
##  [34,] FALSE  FALSE FALSE  FALSE            FALSE
##  [35,] FALSE  FALSE FALSE  FALSE            FALSE
##  [36,] FALSE  FALSE FALSE  FALSE            FALSE
##  [37,] FALSE  FALSE FALSE  FALSE            FALSE
##  [38,] FALSE  FALSE FALSE  FALSE            FALSE
##  [39,] FALSE  FALSE FALSE  FALSE            FALSE
##  [40,] FALSE  FALSE FALSE  FALSE            FALSE
##  [41,] FALSE  FALSE FALSE  FALSE            FALSE
##  [42,] FALSE  FALSE FALSE  FALSE            FALSE
##  [43,] FALSE  FALSE FALSE  FALSE            FALSE
##  [44,] FALSE  FALSE FALSE  FALSE            FALSE
##  [45,] FALSE  FALSE FALSE  FALSE            FALSE
##  [46,] FALSE  FALSE FALSE  FALSE            FALSE
##  [47,] FALSE  FALSE FALSE  FALSE            FALSE
##  [48,] FALSE  FALSE FALSE  FALSE            FALSE
##  [49,] FALSE  FALSE FALSE  FALSE            FALSE
##  [50,] FALSE  FALSE FALSE  FALSE            FALSE
##  [51,] FALSE  FALSE FALSE  FALSE            FALSE
##  [52,] FALSE  FALSE FALSE  FALSE            FALSE
##  [53,] FALSE  FALSE FALSE  FALSE            FALSE
##  [54,] FALSE  FALSE FALSE  FALSE            FALSE
##  [55,] FALSE  FALSE FALSE  FALSE            FALSE
##  [56,] FALSE  FALSE FALSE  FALSE            FALSE
##  [57,] FALSE  FALSE FALSE  FALSE            FALSE
##  [58,] FALSE  FALSE FALSE  FALSE            FALSE
##  [59,] FALSE  FALSE FALSE  FALSE            FALSE
##  [60,] FALSE  FALSE FALSE  FALSE            FALSE
##  [61,] FALSE  FALSE FALSE  FALSE            FALSE
##  [62,] FALSE  FALSE FALSE  FALSE            FALSE
##  [63,] FALSE  FALSE FALSE  FALSE            FALSE
##  [64,] FALSE  FALSE FALSE  FALSE            FALSE
##  [65,] FALSE  FALSE FALSE  FALSE            FALSE
##  [66,] FALSE  FALSE FALSE  FALSE            FALSE
##  [67,] FALSE  FALSE FALSE  FALSE            FALSE
##  [68,] FALSE  FALSE FALSE  FALSE            FALSE
##  [69,] FALSE  FALSE FALSE  FALSE            FALSE
##  [70,] FALSE  FALSE FALSE  FALSE            FALSE
##  [71,] FALSE  FALSE FALSE  FALSE            FALSE
##  [72,] FALSE  FALSE FALSE  FALSE            FALSE
##  [73,] FALSE  FALSE FALSE  FALSE            FALSE
##  [74,] FALSE  FALSE FALSE  FALSE            FALSE
##  [75,] FALSE  FALSE FALSE  FALSE            FALSE
##  [76,] FALSE  FALSE FALSE  FALSE            FALSE
##  [77,] FALSE  FALSE FALSE  FALSE            FALSE
##  [78,] FALSE  FALSE FALSE  FALSE            FALSE
##  [79,] FALSE  FALSE FALSE  FALSE            FALSE
##  [80,] FALSE  FALSE FALSE  FALSE            FALSE
##  [81,] FALSE  FALSE FALSE  FALSE            FALSE
##  [82,] FALSE  FALSE FALSE  FALSE            FALSE
##  [83,] FALSE  FALSE FALSE  FALSE            FALSE
##  [84,] FALSE  FALSE FALSE  FALSE            FALSE
##  [85,] FALSE  FALSE FALSE  FALSE            FALSE
##  [86,] FALSE  FALSE FALSE  FALSE            FALSE
##  [87,] FALSE  FALSE FALSE  FALSE            FALSE
##  [88,] FALSE  FALSE FALSE  FALSE            FALSE
##  [89,] FALSE  FALSE FALSE  FALSE            FALSE
##  [90,] FALSE  FALSE FALSE  FALSE            FALSE
##  [91,] FALSE  FALSE FALSE  FALSE            FALSE
##  [92,] FALSE  FALSE FALSE  FALSE            FALSE
##  [93,] FALSE  FALSE FALSE  FALSE            FALSE
##  [94,] FALSE  FALSE FALSE  FALSE            FALSE
##  [95,] FALSE  FALSE FALSE  FALSE            FALSE
##  [96,] FALSE  FALSE FALSE  FALSE            FALSE
##  [97,] FALSE  FALSE FALSE  FALSE            FALSE
##  [98,] FALSE  FALSE FALSE  FALSE            FALSE
##  [99,] FALSE  FALSE FALSE  FALSE            FALSE
## [100,] FALSE  FALSE FALSE  FALSE            FALSE
## [101,] FALSE  FALSE FALSE  FALSE            FALSE
## [102,] FALSE  FALSE FALSE  FALSE            FALSE
## [103,] FALSE  FALSE FALSE  FALSE            FALSE
## [104,] FALSE  FALSE FALSE  FALSE            FALSE
## [105,] FALSE  FALSE FALSE  FALSE            FALSE
## [106,] FALSE  FALSE FALSE  FALSE            FALSE
## [107,] FALSE  FALSE FALSE  FALSE            FALSE
## [108,] FALSE  FALSE FALSE  FALSE            FALSE
## [109,] FALSE  FALSE FALSE  FALSE            FALSE
## [110,] FALSE  FALSE FALSE  FALSE            FALSE
## [111,] FALSE  FALSE FALSE  FALSE            FALSE
## [112,] FALSE  FALSE FALSE  FALSE            FALSE
## [113,] FALSE  FALSE FALSE  FALSE            FALSE
## [114,] FALSE  FALSE FALSE  FALSE            FALSE
## [115,] FALSE  FALSE FALSE  FALSE            FALSE
## [116,] FALSE  FALSE FALSE  FALSE            FALSE
## [117,] FALSE  FALSE FALSE  FALSE            FALSE
## [118,] FALSE  FALSE FALSE  FALSE            FALSE
## [119,] FALSE  FALSE FALSE  FALSE            FALSE
## [120,] FALSE  FALSE FALSE  FALSE            FALSE
## [121,] FALSE  FALSE FALSE  FALSE            FALSE
## [122,] FALSE  FALSE FALSE  FALSE            FALSE
## [123,] FALSE  FALSE FALSE  FALSE            FALSE
## [124,] FALSE  FALSE FALSE  FALSE            FALSE
## [125,] FALSE  FALSE FALSE  FALSE            FALSE
## [126,] FALSE  FALSE FALSE  FALSE            FALSE
## [127,] FALSE  FALSE FALSE  FALSE            FALSE
## [128,] FALSE  FALSE FALSE  FALSE            FALSE
## [129,] FALSE  FALSE FALSE  FALSE            FALSE
## [130,] FALSE  FALSE FALSE  FALSE            FALSE
## [131,] FALSE  FALSE FALSE  FALSE            FALSE
## [132,] FALSE  FALSE FALSE  FALSE            FALSE
## [133,] FALSE  FALSE FALSE  FALSE            FALSE
## [134,] FALSE  FALSE FALSE  FALSE            FALSE
## [135,] FALSE  FALSE FALSE  FALSE            FALSE
## [136,] FALSE  FALSE FALSE  FALSE            FALSE
## [137,] FALSE  FALSE FALSE  FALSE            FALSE
## [138,] FALSE  FALSE FALSE  FALSE            FALSE
## [139,] FALSE  FALSE FALSE  FALSE            FALSE
## [140,] FALSE  FALSE FALSE  FALSE            FALSE
## [141,] FALSE  FALSE FALSE  FALSE            FALSE
## [142,] FALSE  FALSE FALSE  FALSE            FALSE
## [143,] FALSE  FALSE FALSE  FALSE            FALSE
## [144,] FALSE  FALSE FALSE  FALSE            FALSE
## [145,] FALSE  FALSE FALSE  FALSE            FALSE
## [146,] FALSE  FALSE FALSE  FALSE            FALSE
## [147,] FALSE  FALSE FALSE  FALSE            FALSE
## [148,] FALSE  FALSE FALSE  FALSE            FALSE
## [149,] FALSE  FALSE FALSE  FALSE            FALSE
## [150,] FALSE  FALSE FALSE  FALSE            FALSE
## [151,] FALSE  FALSE FALSE  FALSE            FALSE
## [152,] FALSE  FALSE FALSE  FALSE            FALSE
## [153,] FALSE  FALSE FALSE  FALSE            FALSE
## [154,] FALSE  FALSE FALSE  FALSE            FALSE
## [155,] FALSE  FALSE FALSE  FALSE            FALSE
## [156,] FALSE  FALSE FALSE  FALSE            FALSE
## [157,] FALSE  FALSE FALSE  FALSE            FALSE
## [158,] FALSE  FALSE FALSE  FALSE            FALSE
## [159,] FALSE  FALSE FALSE  FALSE            FALSE
## [160,] FALSE  FALSE FALSE  FALSE            FALSE
## [161,] FALSE  FALSE FALSE  FALSE            FALSE
## [162,] FALSE  FALSE FALSE  FALSE            FALSE
## [163,] FALSE  FALSE FALSE  FALSE            FALSE
## [164,] FALSE  FALSE FALSE  FALSE            FALSE
## [165,] FALSE  FALSE FALSE  FALSE            FALSE
## [166,] FALSE  FALSE FALSE  FALSE            FALSE
## [167,] FALSE  FALSE FALSE  FALSE            FALSE
## [168,] FALSE  FALSE FALSE  FALSE            FALSE
## [169,] FALSE  FALSE FALSE  FALSE            FALSE
## [170,] FALSE  FALSE FALSE  FALSE            FALSE
## [171,] FALSE  FALSE FALSE  FALSE            FALSE
## [172,] FALSE  FALSE FALSE  FALSE            FALSE
## [173,] FALSE  FALSE FALSE  FALSE            FALSE
## [174,] FALSE  FALSE FALSE  FALSE            FALSE
## [175,] FALSE  FALSE FALSE  FALSE            FALSE
## [176,] FALSE  FALSE FALSE  FALSE            FALSE
## [177,] FALSE  FALSE FALSE  FALSE            FALSE
## [178,] FALSE  FALSE FALSE  FALSE            FALSE
## [179,] FALSE  FALSE FALSE  FALSE            FALSE
## [180,] FALSE  FALSE FALSE  FALSE            FALSE
## [181,] FALSE  FALSE FALSE  FALSE            FALSE
## [182,] FALSE  FALSE FALSE  FALSE            FALSE
## [183,] FALSE  FALSE FALSE  FALSE            FALSE
## [184,] FALSE  FALSE FALSE  FALSE            FALSE
## [185,] FALSE  FALSE FALSE  FALSE            FALSE
## [186,] FALSE  FALSE FALSE  FALSE            FALSE
## [187,] FALSE  FALSE FALSE  FALSE            FALSE
## [188,] FALSE  FALSE FALSE  FALSE            FALSE
## [189,] FALSE  FALSE FALSE  FALSE            FALSE
## [190,] FALSE  FALSE FALSE  FALSE            FALSE
\end{verbatim}

\begin{verbatim}
## integer(0)
\end{verbatim}

\begin{verbatim}
## 'data.frame':    125 obs. of  5 variables:
##  $ Code            : chr  "Phase\\lesson begin" "speaking time\\teacher" "speaking time\\student" "speaking time\\teacher" ...
##  $ Anfang          : chr  "0:00:41,5" "0:00:41,8" "0:00:42,3" "0:00:45,9" ...
##  $ Ende            : chr  "0:00:41,7" "0:00:42,3" "0:00:44,7" "0:00:47,6" ...
##  $ Fläche          : chr  "00:00:00,2" "00:00:00,5" "00:00:02,3" "00:00:01,6" ...
##  $ Abdeckungsgrad..: num  0.03 0.07 0.32 0.23 0.41 2.17 0.47 0.11 0.27 4.01 ...
\end{verbatim}

\begin{verbatim}
##         Code Anfang  Ende Fläche Abdeckungsgrad..
##   [1,] FALSE  FALSE FALSE  FALSE            FALSE
##   [2,] FALSE  FALSE FALSE  FALSE            FALSE
##   [3,] FALSE  FALSE FALSE  FALSE            FALSE
##   [4,] FALSE  FALSE FALSE  FALSE            FALSE
##   [5,] FALSE  FALSE FALSE  FALSE            FALSE
##   [6,] FALSE  FALSE FALSE  FALSE            FALSE
##   [7,] FALSE  FALSE FALSE  FALSE            FALSE
##   [8,] FALSE  FALSE FALSE  FALSE            FALSE
##   [9,] FALSE  FALSE FALSE  FALSE            FALSE
##  [10,] FALSE  FALSE FALSE  FALSE            FALSE
##  [11,] FALSE  FALSE FALSE  FALSE            FALSE
##  [12,] FALSE  FALSE FALSE  FALSE            FALSE
##  [13,] FALSE  FALSE FALSE  FALSE            FALSE
##  [14,] FALSE  FALSE FALSE  FALSE            FALSE
##  [15,] FALSE  FALSE FALSE  FALSE            FALSE
##  [16,] FALSE  FALSE FALSE  FALSE            FALSE
##  [17,] FALSE  FALSE FALSE  FALSE            FALSE
##  [18,] FALSE  FALSE FALSE  FALSE            FALSE
##  [19,] FALSE  FALSE FALSE  FALSE            FALSE
##  [20,] FALSE  FALSE FALSE  FALSE            FALSE
##  [21,] FALSE  FALSE FALSE  FALSE            FALSE
##  [22,] FALSE  FALSE FALSE  FALSE            FALSE
##  [23,] FALSE  FALSE FALSE  FALSE            FALSE
##  [24,] FALSE  FALSE FALSE  FALSE            FALSE
##  [25,] FALSE  FALSE FALSE  FALSE            FALSE
##  [26,] FALSE  FALSE FALSE  FALSE            FALSE
##  [27,] FALSE  FALSE FALSE  FALSE            FALSE
##  [28,] FALSE  FALSE FALSE  FALSE            FALSE
##  [29,] FALSE  FALSE FALSE  FALSE            FALSE
##  [30,] FALSE  FALSE FALSE  FALSE            FALSE
##  [31,] FALSE  FALSE FALSE  FALSE            FALSE
##  [32,] FALSE  FALSE FALSE  FALSE            FALSE
##  [33,] FALSE  FALSE FALSE  FALSE            FALSE
##  [34,] FALSE  FALSE FALSE  FALSE            FALSE
##  [35,] FALSE  FALSE FALSE  FALSE            FALSE
##  [36,] FALSE  FALSE FALSE  FALSE            FALSE
##  [37,] FALSE  FALSE FALSE  FALSE            FALSE
##  [38,] FALSE  FALSE FALSE  FALSE            FALSE
##  [39,] FALSE  FALSE FALSE  FALSE            FALSE
##  [40,] FALSE  FALSE FALSE  FALSE            FALSE
##  [41,] FALSE  FALSE FALSE  FALSE            FALSE
##  [42,] FALSE  FALSE FALSE  FALSE            FALSE
##  [43,] FALSE  FALSE FALSE  FALSE            FALSE
##  [44,] FALSE  FALSE FALSE  FALSE            FALSE
##  [45,] FALSE  FALSE FALSE  FALSE            FALSE
##  [46,] FALSE  FALSE FALSE  FALSE            FALSE
##  [47,] FALSE  FALSE FALSE  FALSE            FALSE
##  [48,] FALSE  FALSE FALSE  FALSE            FALSE
##  [49,] FALSE  FALSE FALSE  FALSE            FALSE
##  [50,] FALSE  FALSE FALSE  FALSE            FALSE
##  [51,] FALSE  FALSE FALSE  FALSE            FALSE
##  [52,] FALSE  FALSE FALSE  FALSE            FALSE
##  [53,] FALSE  FALSE FALSE  FALSE            FALSE
##  [54,] FALSE  FALSE FALSE  FALSE            FALSE
##  [55,] FALSE  FALSE FALSE  FALSE            FALSE
##  [56,] FALSE  FALSE FALSE  FALSE            FALSE
##  [57,] FALSE  FALSE FALSE  FALSE            FALSE
##  [58,] FALSE  FALSE FALSE  FALSE            FALSE
##  [59,] FALSE  FALSE FALSE  FALSE            FALSE
##  [60,] FALSE  FALSE FALSE  FALSE            FALSE
##  [61,] FALSE  FALSE FALSE  FALSE            FALSE
##  [62,] FALSE  FALSE FALSE  FALSE            FALSE
##  [63,] FALSE  FALSE FALSE  FALSE            FALSE
##  [64,] FALSE  FALSE FALSE  FALSE            FALSE
##  [65,] FALSE  FALSE FALSE  FALSE            FALSE
##  [66,] FALSE  FALSE FALSE  FALSE            FALSE
##  [67,] FALSE  FALSE FALSE  FALSE            FALSE
##  [68,] FALSE  FALSE FALSE  FALSE            FALSE
##  [69,] FALSE  FALSE FALSE  FALSE            FALSE
##  [70,] FALSE  FALSE FALSE  FALSE            FALSE
##  [71,] FALSE  FALSE FALSE  FALSE            FALSE
##  [72,] FALSE  FALSE FALSE  FALSE            FALSE
##  [73,] FALSE  FALSE FALSE  FALSE            FALSE
##  [74,] FALSE  FALSE FALSE  FALSE            FALSE
##  [75,] FALSE  FALSE FALSE  FALSE            FALSE
##  [76,] FALSE  FALSE FALSE  FALSE            FALSE
##  [77,] FALSE  FALSE FALSE  FALSE            FALSE
##  [78,] FALSE  FALSE FALSE  FALSE            FALSE
##  [79,] FALSE  FALSE FALSE  FALSE            FALSE
##  [80,] FALSE  FALSE FALSE  FALSE            FALSE
##  [81,] FALSE  FALSE FALSE  FALSE            FALSE
##  [82,] FALSE  FALSE FALSE  FALSE            FALSE
##  [83,] FALSE  FALSE FALSE  FALSE            FALSE
##  [84,] FALSE  FALSE FALSE  FALSE            FALSE
##  [85,] FALSE  FALSE FALSE  FALSE            FALSE
##  [86,] FALSE  FALSE FALSE  FALSE            FALSE
##  [87,] FALSE  FALSE FALSE  FALSE            FALSE
##  [88,] FALSE  FALSE FALSE  FALSE            FALSE
##  [89,] FALSE  FALSE FALSE  FALSE            FALSE
##  [90,] FALSE  FALSE FALSE  FALSE            FALSE
##  [91,] FALSE  FALSE FALSE  FALSE            FALSE
##  [92,] FALSE  FALSE FALSE  FALSE            FALSE
##  [93,] FALSE  FALSE FALSE  FALSE            FALSE
##  [94,] FALSE  FALSE FALSE  FALSE            FALSE
##  [95,] FALSE  FALSE FALSE  FALSE            FALSE
##  [96,] FALSE  FALSE FALSE  FALSE            FALSE
##  [97,] FALSE  FALSE FALSE  FALSE            FALSE
##  [98,] FALSE  FALSE FALSE  FALSE            FALSE
##  [99,] FALSE  FALSE FALSE  FALSE            FALSE
## [100,] FALSE  FALSE FALSE  FALSE            FALSE
## [101,] FALSE  FALSE FALSE  FALSE            FALSE
## [102,] FALSE  FALSE FALSE  FALSE            FALSE
## [103,] FALSE  FALSE FALSE  FALSE            FALSE
## [104,] FALSE  FALSE FALSE  FALSE            FALSE
## [105,] FALSE  FALSE FALSE  FALSE            FALSE
## [106,] FALSE  FALSE FALSE  FALSE            FALSE
## [107,] FALSE  FALSE FALSE  FALSE            FALSE
## [108,] FALSE  FALSE FALSE  FALSE            FALSE
## [109,] FALSE  FALSE FALSE  FALSE            FALSE
## [110,] FALSE  FALSE FALSE  FALSE            FALSE
## [111,] FALSE  FALSE FALSE  FALSE            FALSE
## [112,] FALSE  FALSE FALSE  FALSE            FALSE
## [113,] FALSE  FALSE FALSE  FALSE            FALSE
## [114,] FALSE  FALSE FALSE  FALSE            FALSE
## [115,] FALSE  FALSE FALSE  FALSE            FALSE
## [116,] FALSE  FALSE FALSE  FALSE            FALSE
## [117,] FALSE  FALSE FALSE  FALSE            FALSE
## [118,] FALSE  FALSE FALSE  FALSE            FALSE
## [119,] FALSE  FALSE FALSE  FALSE            FALSE
## [120,] FALSE  FALSE FALSE  FALSE            FALSE
## [121,] FALSE  FALSE FALSE  FALSE            FALSE
## [122,] FALSE  FALSE FALSE  FALSE            FALSE
## [123,] FALSE  FALSE FALSE  FALSE            FALSE
## [124,] FALSE  FALSE FALSE  FALSE            FALSE
## [125,] FALSE  FALSE FALSE  FALSE            FALSE
\end{verbatim}

\begin{verbatim}
## integer(0)
\end{verbatim}

\begin{verbatim}
## 'data.frame':    425 obs. of  6 variables:
##  $ Dokumentgruppe  : chr  "kodiert von Anna" "kodiert von Anna" "kodiert von Anna" "kodiert von Anna" ...
##  $ Code            : chr  "Phase\\lesson begin" "speaking time\\teacher" "speaking time\\teacher" "speaking time\\student" ...
##  $ Anfang          : chr  "0:00:10,8" "0:00:10,9" "0:00:15,7" "0:00:19,2" ...
##  $ Ende            : chr  "0:00:11,1" "0:00:14,8" "0:00:19,0" "0:00:20,7" ...
##  $ Fläche          : chr  "00:00:00,2" "00:00:03,8" "00:00:03,3" "00:00:01,5" ...
##  $ Abdeckungsgrad..: num  0.03 0.56 0.49 0.22 1.45 1.74 2.59 2.82 0.09 0.04 ...
\end{verbatim}

\begin{verbatim}
##        Dokumentgruppe  Code Anfang  Ende Fläche Abdeckungsgrad..
##   [1,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [2,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [3,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [4,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [5,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [6,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [7,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [8,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [9,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [10,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [11,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [12,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [13,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [14,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [15,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [16,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [17,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [18,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [19,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [20,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [21,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [22,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [23,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [24,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [25,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [26,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [27,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [28,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [29,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [30,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [31,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [32,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [33,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [34,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [35,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [36,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [37,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [38,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [39,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [40,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [41,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [42,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [43,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [44,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [45,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [46,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [47,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [48,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [49,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [50,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [51,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [52,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [53,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [54,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [55,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [56,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [57,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [58,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [59,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [60,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [61,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [62,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [63,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [64,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [65,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [66,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [67,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [68,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [69,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [70,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [71,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [72,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [73,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [74,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [75,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [76,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [77,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [78,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [79,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [80,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [81,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [82,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [83,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [84,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [85,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [86,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [87,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [88,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [89,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [90,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [91,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [92,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [93,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [94,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [95,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [96,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [97,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [98,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [99,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [100,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [101,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [102,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [103,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [104,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [105,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [106,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [107,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [108,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [109,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [110,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [111,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [112,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [113,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [114,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [115,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [116,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [117,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [118,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [119,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [120,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [121,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [122,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [123,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [124,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [125,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [126,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [127,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [128,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [129,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [130,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [131,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [132,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [133,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [134,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [135,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [136,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [137,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [138,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [139,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [140,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [141,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [142,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [143,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [144,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [145,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [146,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [147,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [148,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [149,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [150,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [151,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [152,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [153,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [154,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [155,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [156,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [157,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [158,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [159,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [160,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [161,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [162,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [163,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [164,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [165,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [166,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [167,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [168,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [169,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [170,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [171,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [172,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [173,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [174,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [175,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [176,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [177,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [178,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [179,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [180,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [181,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [182,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [183,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [184,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [185,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [186,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [187,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [188,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [189,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [190,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [191,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [192,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [193,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [194,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [195,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [196,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [197,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [198,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [199,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [200,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [201,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [202,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [203,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [204,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [205,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [206,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [207,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [208,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [209,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [210,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [211,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [212,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [213,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [214,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [215,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [216,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [217,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [218,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [219,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [220,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [221,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [222,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [223,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [224,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [225,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [226,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [227,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [228,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [229,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [230,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [231,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [232,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [233,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [234,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [235,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [236,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [237,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [238,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [239,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [240,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [241,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [242,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [243,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [244,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [245,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [246,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [247,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [248,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [249,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [250,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [251,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [252,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [253,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [254,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [255,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [256,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [257,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [258,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [259,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [260,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [261,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [262,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [263,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [264,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [265,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [266,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [267,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [268,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [269,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [270,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [271,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [272,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [273,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [274,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [275,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [276,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [277,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [278,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [279,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [280,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [281,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [282,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [283,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [284,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [285,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [286,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [287,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [288,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [289,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [290,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [291,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [292,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [293,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [294,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [295,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [296,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [297,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [298,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [299,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [300,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [301,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [302,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [303,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [304,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [305,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [306,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [307,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [308,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [309,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [310,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [311,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [312,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [313,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [314,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [315,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [316,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [317,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [318,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [319,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [320,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [321,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [322,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [323,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [324,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [325,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [326,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [327,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [328,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [329,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [330,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [331,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [332,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [333,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [334,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [335,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [336,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [337,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [338,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [339,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [340,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [341,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [342,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [343,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [344,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [345,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [346,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [347,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [348,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [349,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [350,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [351,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [352,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [353,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [354,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [355,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [356,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [357,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [358,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [359,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [360,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [361,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [362,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [363,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [364,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [365,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [366,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [367,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [368,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [369,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [370,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [371,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [372,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [373,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [374,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [375,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [376,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [377,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [378,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [379,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [380,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [381,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [382,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [383,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [384,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [385,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [386,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [387,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [388,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [389,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [390,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [391,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [392,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [393,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [394,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [395,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [396,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [397,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [398,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [399,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [400,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [401,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [402,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [403,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [404,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [405,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [406,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [407,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [408,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [409,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [410,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [411,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [412,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [413,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [414,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [415,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [416,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [417,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [418,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [419,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [420,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [421,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [422,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [423,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [424,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [425,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
\end{verbatim}

\begin{verbatim}
## integer(0)
\end{verbatim}

\begin{verbatim}
## 'data.frame':    335 obs. of  6 variables:
##  $ Dokumentgruppe  : chr  "02_03_kodiert von Mandy" "02_03_kodiert von Mandy" "02_03_kodiert von Mandy" "02_03_kodiert von Mandy" ...
##  $ Code            : chr  "Phase\\lesson begin" "speaking time\\teachter" "Phase\\teachers lecture" "speaking time\\teachter" ...
##  $ Anfang          : chr  "0:00:14,7" "0:00:15,0" "0:00:22,0" "0:00:22,1" ...
##  $ Ende            : chr  "0:00:15,0" "0:00:20,7" "0:00:55,2" "0:00:28,0" ...
##  $ Fläche          : chr  "00:00:00,3" "00:00:05,7" "00:00:33,2" "00:00:05,8" ...
##  $ Abdeckungsgrad..: num  0.04 0.84 4.89 0.86 3.71 ...
\end{verbatim}

\begin{verbatim}
##        Dokumentgruppe  Code Anfang  Ende Fläche Abdeckungsgrad..
##   [1,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [2,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [3,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [4,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [5,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [6,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [7,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [8,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##   [9,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [10,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [11,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [12,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [13,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [14,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [15,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [16,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [17,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [18,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [19,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [20,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [21,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [22,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [23,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [24,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [25,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [26,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [27,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [28,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [29,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [30,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [31,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [32,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [33,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [34,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [35,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [36,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [37,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [38,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [39,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [40,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [41,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [42,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [43,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [44,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [45,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [46,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [47,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [48,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [49,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [50,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [51,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [52,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [53,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [54,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [55,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [56,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [57,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [58,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [59,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [60,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [61,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [62,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [63,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [64,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [65,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [66,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [67,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [68,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [69,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [70,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [71,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [72,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [73,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [74,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [75,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [76,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [77,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [78,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [79,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [80,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [81,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [82,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [83,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [84,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [85,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [86,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [87,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [88,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [89,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [90,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [91,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [92,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [93,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [94,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [95,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [96,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [97,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [98,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
##  [99,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [100,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [101,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [102,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [103,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [104,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [105,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [106,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [107,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [108,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [109,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [110,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [111,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [112,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [113,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [114,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [115,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [116,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [117,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [118,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [119,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [120,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [121,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [122,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [123,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [124,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [125,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [126,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [127,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [128,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [129,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [130,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [131,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [132,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [133,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [134,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [135,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [136,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [137,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [138,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [139,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [140,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [141,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [142,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [143,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [144,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [145,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [146,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [147,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [148,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [149,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [150,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [151,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [152,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [153,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [154,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [155,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [156,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [157,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [158,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [159,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [160,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [161,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [162,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [163,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [164,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [165,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [166,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [167,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [168,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [169,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [170,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [171,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [172,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [173,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [174,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [175,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [176,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [177,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [178,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [179,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [180,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [181,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [182,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [183,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [184,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [185,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [186,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [187,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [188,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [189,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [190,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [191,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [192,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [193,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [194,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [195,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [196,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [197,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [198,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [199,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [200,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [201,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [202,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [203,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [204,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [205,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [206,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [207,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [208,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [209,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [210,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [211,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [212,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [213,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [214,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [215,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [216,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [217,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [218,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [219,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [220,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [221,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [222,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [223,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [224,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [225,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [226,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [227,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [228,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [229,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [230,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [231,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [232,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [233,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [234,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [235,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [236,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [237,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [238,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [239,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [240,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [241,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [242,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [243,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [244,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [245,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [246,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [247,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [248,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [249,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [250,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [251,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [252,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [253,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [254,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [255,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [256,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [257,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [258,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [259,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [260,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [261,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [262,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [263,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [264,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [265,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [266,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [267,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [268,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [269,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [270,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [271,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [272,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [273,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [274,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [275,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [276,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [277,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [278,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [279,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [280,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [281,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [282,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [283,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [284,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [285,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [286,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [287,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [288,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [289,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [290,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [291,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [292,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [293,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [294,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [295,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [296,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [297,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [298,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [299,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [300,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [301,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [302,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [303,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [304,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [305,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [306,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [307,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [308,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [309,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [310,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [311,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [312,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [313,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [314,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [315,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [316,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [317,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [318,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [319,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [320,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [321,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [322,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [323,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [324,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [325,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [326,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [327,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [328,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [329,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [330,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [331,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [332,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [333,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [334,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
## [335,]          FALSE FALSE  FALSE FALSE  FALSE            FALSE
\end{verbatim}

\begin{verbatim}
## integer(0)
\end{verbatim}

\begin{verbatim}
## 'data.frame':    271 obs. of  5 variables:
##  $ Code            : chr  "Phase\\lesson begin" "speaking time\\teachter" "speaking time\\student" "speaking time\\teachter" ...
##  $ Anfang          : chr  "0:00:17,1" "0:00:17,1" "0:00:21,6" "0:00:24,6" ...
##  $ Ende            : chr  "0:00:17,4" "0:00:19,9" "0:00:22,8" "0:00:25,5" ...
##  $ Fläche          : chr  "00:00:00,2" "00:00:02,7" "00:00:01,1" "00:00:00,8" ...
##  $ Abdeckungsgrad..: num  0.04 0.39 0.16 0.12 0.37 0.47 2.05 2.3 0.13 0.14 ...
\end{verbatim}

\begin{verbatim}
##         Code Anfang  Ende Fläche Abdeckungsgrad..
##   [1,] FALSE  FALSE FALSE  FALSE            FALSE
##   [2,] FALSE  FALSE FALSE  FALSE            FALSE
##   [3,] FALSE  FALSE FALSE  FALSE            FALSE
##   [4,] FALSE  FALSE FALSE  FALSE            FALSE
##   [5,] FALSE  FALSE FALSE  FALSE            FALSE
##   [6,] FALSE  FALSE FALSE  FALSE            FALSE
##   [7,] FALSE  FALSE FALSE  FALSE            FALSE
##   [8,] FALSE  FALSE FALSE  FALSE            FALSE
##   [9,] FALSE  FALSE FALSE  FALSE            FALSE
##  [10,] FALSE  FALSE FALSE  FALSE            FALSE
##  [11,] FALSE  FALSE FALSE  FALSE            FALSE
##  [12,] FALSE  FALSE FALSE  FALSE            FALSE
##  [13,] FALSE  FALSE FALSE  FALSE            FALSE
##  [14,] FALSE  FALSE FALSE  FALSE            FALSE
##  [15,] FALSE  FALSE FALSE  FALSE            FALSE
##  [16,] FALSE  FALSE FALSE  FALSE            FALSE
##  [17,] FALSE  FALSE FALSE  FALSE            FALSE
##  [18,] FALSE  FALSE FALSE  FALSE            FALSE
##  [19,] FALSE  FALSE FALSE  FALSE            FALSE
##  [20,] FALSE  FALSE FALSE  FALSE            FALSE
##  [21,] FALSE  FALSE FALSE  FALSE            FALSE
##  [22,] FALSE  FALSE FALSE  FALSE            FALSE
##  [23,] FALSE  FALSE FALSE  FALSE            FALSE
##  [24,] FALSE  FALSE FALSE  FALSE            FALSE
##  [25,] FALSE  FALSE FALSE  FALSE            FALSE
##  [26,] FALSE  FALSE FALSE  FALSE            FALSE
##  [27,] FALSE  FALSE FALSE  FALSE            FALSE
##  [28,] FALSE  FALSE FALSE  FALSE            FALSE
##  [29,] FALSE  FALSE FALSE  FALSE            FALSE
##  [30,] FALSE  FALSE FALSE  FALSE            FALSE
##  [31,] FALSE  FALSE FALSE  FALSE            FALSE
##  [32,] FALSE  FALSE FALSE  FALSE            FALSE
##  [33,] FALSE  FALSE FALSE  FALSE            FALSE
##  [34,] FALSE  FALSE FALSE  FALSE            FALSE
##  [35,] FALSE  FALSE FALSE  FALSE            FALSE
##  [36,] FALSE  FALSE FALSE  FALSE            FALSE
##  [37,] FALSE  FALSE FALSE  FALSE            FALSE
##  [38,] FALSE  FALSE FALSE  FALSE            FALSE
##  [39,] FALSE  FALSE FALSE  FALSE            FALSE
##  [40,] FALSE  FALSE FALSE  FALSE            FALSE
##  [41,] FALSE  FALSE FALSE  FALSE            FALSE
##  [42,] FALSE  FALSE FALSE  FALSE            FALSE
##  [43,] FALSE  FALSE FALSE  FALSE            FALSE
##  [44,] FALSE  FALSE FALSE  FALSE            FALSE
##  [45,] FALSE  FALSE FALSE  FALSE            FALSE
##  [46,] FALSE  FALSE FALSE  FALSE            FALSE
##  [47,] FALSE  FALSE FALSE  FALSE            FALSE
##  [48,] FALSE  FALSE FALSE  FALSE            FALSE
##  [49,] FALSE  FALSE FALSE  FALSE            FALSE
##  [50,] FALSE  FALSE FALSE  FALSE            FALSE
##  [51,] FALSE  FALSE FALSE  FALSE            FALSE
##  [52,] FALSE  FALSE FALSE  FALSE            FALSE
##  [53,] FALSE  FALSE FALSE  FALSE            FALSE
##  [54,] FALSE  FALSE FALSE  FALSE            FALSE
##  [55,] FALSE  FALSE FALSE  FALSE            FALSE
##  [56,] FALSE  FALSE FALSE  FALSE            FALSE
##  [57,] FALSE  FALSE FALSE  FALSE            FALSE
##  [58,] FALSE  FALSE FALSE  FALSE            FALSE
##  [59,] FALSE  FALSE FALSE  FALSE            FALSE
##  [60,] FALSE  FALSE FALSE  FALSE            FALSE
##  [61,] FALSE  FALSE FALSE  FALSE            FALSE
##  [62,] FALSE  FALSE FALSE  FALSE            FALSE
##  [63,] FALSE  FALSE FALSE  FALSE            FALSE
##  [64,] FALSE  FALSE FALSE  FALSE            FALSE
##  [65,] FALSE  FALSE FALSE  FALSE            FALSE
##  [66,] FALSE  FALSE FALSE  FALSE            FALSE
##  [67,] FALSE  FALSE FALSE  FALSE            FALSE
##  [68,] FALSE  FALSE FALSE  FALSE            FALSE
##  [69,] FALSE  FALSE FALSE  FALSE            FALSE
##  [70,] FALSE  FALSE FALSE  FALSE            FALSE
##  [71,] FALSE  FALSE FALSE  FALSE            FALSE
##  [72,] FALSE  FALSE FALSE  FALSE            FALSE
##  [73,] FALSE  FALSE FALSE  FALSE            FALSE
##  [74,] FALSE  FALSE FALSE  FALSE            FALSE
##  [75,] FALSE  FALSE FALSE  FALSE            FALSE
##  [76,] FALSE  FALSE FALSE  FALSE            FALSE
##  [77,] FALSE  FALSE FALSE  FALSE            FALSE
##  [78,] FALSE  FALSE FALSE  FALSE            FALSE
##  [79,] FALSE  FALSE FALSE  FALSE            FALSE
##  [80,] FALSE  FALSE FALSE  FALSE            FALSE
##  [81,] FALSE  FALSE FALSE  FALSE            FALSE
##  [82,] FALSE  FALSE FALSE  FALSE            FALSE
##  [83,] FALSE  FALSE FALSE  FALSE            FALSE
##  [84,] FALSE  FALSE FALSE  FALSE            FALSE
##  [85,] FALSE  FALSE FALSE  FALSE            FALSE
##  [86,] FALSE  FALSE FALSE  FALSE            FALSE
##  [87,] FALSE  FALSE FALSE  FALSE            FALSE
##  [88,] FALSE  FALSE FALSE  FALSE            FALSE
##  [89,] FALSE  FALSE FALSE  FALSE            FALSE
##  [90,] FALSE  FALSE FALSE  FALSE            FALSE
##  [91,] FALSE  FALSE FALSE  FALSE            FALSE
##  [92,] FALSE  FALSE FALSE  FALSE            FALSE
##  [93,] FALSE  FALSE FALSE  FALSE            FALSE
##  [94,] FALSE  FALSE FALSE  FALSE            FALSE
##  [95,] FALSE  FALSE FALSE  FALSE            FALSE
##  [96,] FALSE  FALSE FALSE  FALSE            FALSE
##  [97,] FALSE  FALSE FALSE  FALSE            FALSE
##  [98,] FALSE  FALSE FALSE  FALSE            FALSE
##  [99,] FALSE  FALSE FALSE  FALSE            FALSE
## [100,] FALSE  FALSE FALSE  FALSE            FALSE
## [101,] FALSE  FALSE FALSE  FALSE            FALSE
## [102,] FALSE  FALSE FALSE  FALSE            FALSE
## [103,] FALSE  FALSE FALSE  FALSE            FALSE
## [104,] FALSE  FALSE FALSE  FALSE            FALSE
## [105,] FALSE  FALSE FALSE  FALSE            FALSE
## [106,] FALSE  FALSE FALSE  FALSE            FALSE
## [107,] FALSE  FALSE FALSE  FALSE            FALSE
## [108,] FALSE  FALSE FALSE  FALSE            FALSE
## [109,] FALSE  FALSE FALSE  FALSE            FALSE
## [110,] FALSE  FALSE FALSE  FALSE            FALSE
## [111,] FALSE  FALSE FALSE  FALSE            FALSE
## [112,] FALSE  FALSE FALSE  FALSE            FALSE
## [113,] FALSE  FALSE FALSE  FALSE            FALSE
## [114,] FALSE  FALSE FALSE  FALSE            FALSE
## [115,] FALSE  FALSE FALSE  FALSE            FALSE
## [116,] FALSE  FALSE FALSE  FALSE            FALSE
## [117,] FALSE  FALSE FALSE  FALSE            FALSE
## [118,] FALSE  FALSE FALSE  FALSE            FALSE
## [119,] FALSE  FALSE FALSE  FALSE            FALSE
## [120,] FALSE  FALSE FALSE  FALSE            FALSE
## [121,] FALSE  FALSE FALSE  FALSE            FALSE
## [122,] FALSE  FALSE FALSE  FALSE            FALSE
## [123,] FALSE  FALSE FALSE  FALSE            FALSE
## [124,] FALSE  FALSE FALSE  FALSE            FALSE
## [125,] FALSE  FALSE FALSE  FALSE            FALSE
## [126,] FALSE  FALSE FALSE  FALSE            FALSE
## [127,] FALSE  FALSE FALSE  FALSE            FALSE
## [128,] FALSE  FALSE FALSE  FALSE            FALSE
## [129,] FALSE  FALSE FALSE  FALSE            FALSE
## [130,] FALSE  FALSE FALSE  FALSE            FALSE
## [131,] FALSE  FALSE FALSE  FALSE            FALSE
## [132,] FALSE  FALSE FALSE  FALSE            FALSE
## [133,] FALSE  FALSE FALSE  FALSE            FALSE
## [134,] FALSE  FALSE FALSE  FALSE            FALSE
## [135,] FALSE  FALSE FALSE  FALSE            FALSE
## [136,] FALSE  FALSE FALSE  FALSE            FALSE
## [137,] FALSE  FALSE FALSE  FALSE            FALSE
## [138,] FALSE  FALSE FALSE  FALSE            FALSE
## [139,] FALSE  FALSE FALSE  FALSE            FALSE
## [140,] FALSE  FALSE FALSE  FALSE            FALSE
## [141,] FALSE  FALSE FALSE  FALSE            FALSE
## [142,] FALSE  FALSE FALSE  FALSE            FALSE
## [143,] FALSE  FALSE FALSE  FALSE            FALSE
## [144,] FALSE  FALSE FALSE  FALSE            FALSE
## [145,] FALSE  FALSE FALSE  FALSE            FALSE
## [146,] FALSE  FALSE FALSE  FALSE            FALSE
## [147,] FALSE  FALSE FALSE  FALSE            FALSE
## [148,] FALSE  FALSE FALSE  FALSE            FALSE
## [149,] FALSE  FALSE FALSE  FALSE            FALSE
## [150,] FALSE  FALSE FALSE  FALSE            FALSE
## [151,] FALSE  FALSE FALSE  FALSE            FALSE
## [152,] FALSE  FALSE FALSE  FALSE            FALSE
## [153,] FALSE  FALSE FALSE  FALSE            FALSE
## [154,] FALSE  FALSE FALSE  FALSE            FALSE
## [155,] FALSE  FALSE FALSE  FALSE            FALSE
## [156,] FALSE  FALSE FALSE  FALSE            FALSE
## [157,] FALSE  FALSE FALSE  FALSE            FALSE
## [158,] FALSE  FALSE FALSE  FALSE            FALSE
## [159,] FALSE  FALSE FALSE  FALSE            FALSE
## [160,] FALSE  FALSE FALSE  FALSE            FALSE
## [161,] FALSE  FALSE FALSE  FALSE            FALSE
## [162,] FALSE  FALSE FALSE  FALSE            FALSE
## [163,] FALSE  FALSE FALSE  FALSE            FALSE
## [164,] FALSE  FALSE FALSE  FALSE            FALSE
## [165,] FALSE  FALSE FALSE  FALSE            FALSE
## [166,] FALSE  FALSE FALSE  FALSE            FALSE
## [167,] FALSE  FALSE FALSE  FALSE            FALSE
## [168,] FALSE  FALSE FALSE  FALSE            FALSE
## [169,] FALSE  FALSE FALSE  FALSE            FALSE
## [170,] FALSE  FALSE FALSE  FALSE            FALSE
## [171,] FALSE  FALSE FALSE  FALSE            FALSE
## [172,] FALSE  FALSE FALSE  FALSE            FALSE
## [173,] FALSE  FALSE FALSE  FALSE            FALSE
## [174,] FALSE  FALSE FALSE  FALSE            FALSE
## [175,] FALSE  FALSE FALSE  FALSE            FALSE
## [176,] FALSE  FALSE FALSE  FALSE            FALSE
## [177,] FALSE  FALSE FALSE  FALSE            FALSE
## [178,] FALSE  FALSE FALSE  FALSE            FALSE
## [179,] FALSE  FALSE FALSE  FALSE            FALSE
## [180,] FALSE  FALSE FALSE  FALSE            FALSE
## [181,] FALSE  FALSE FALSE  FALSE            FALSE
## [182,] FALSE  FALSE FALSE  FALSE            FALSE
## [183,] FALSE  FALSE FALSE  FALSE            FALSE
## [184,] FALSE  FALSE FALSE  FALSE            FALSE
## [185,] FALSE  FALSE FALSE  FALSE            FALSE
## [186,] FALSE  FALSE FALSE  FALSE            FALSE
## [187,] FALSE  FALSE FALSE  FALSE            FALSE
## [188,] FALSE  FALSE FALSE  FALSE            FALSE
## [189,] FALSE  FALSE FALSE  FALSE            FALSE
## [190,] FALSE  FALSE FALSE  FALSE            FALSE
## [191,] FALSE  FALSE FALSE  FALSE            FALSE
## [192,] FALSE  FALSE FALSE  FALSE            FALSE
## [193,] FALSE  FALSE FALSE  FALSE            FALSE
## [194,] FALSE  FALSE FALSE  FALSE            FALSE
## [195,] FALSE  FALSE FALSE  FALSE            FALSE
## [196,] FALSE  FALSE FALSE  FALSE            FALSE
## [197,] FALSE  FALSE FALSE  FALSE            FALSE
## [198,] FALSE  FALSE FALSE  FALSE            FALSE
## [199,] FALSE  FALSE FALSE  FALSE            FALSE
## [200,] FALSE  FALSE FALSE  FALSE            FALSE
## [201,] FALSE  FALSE FALSE  FALSE            FALSE
## [202,] FALSE  FALSE FALSE  FALSE            FALSE
## [203,] FALSE  FALSE FALSE  FALSE            FALSE
## [204,] FALSE  FALSE FALSE  FALSE            FALSE
## [205,] FALSE  FALSE FALSE  FALSE            FALSE
## [206,] FALSE  FALSE FALSE  FALSE            FALSE
## [207,] FALSE  FALSE FALSE  FALSE            FALSE
## [208,] FALSE  FALSE FALSE  FALSE            FALSE
## [209,] FALSE  FALSE FALSE  FALSE            FALSE
## [210,] FALSE  FALSE FALSE  FALSE            FALSE
## [211,] FALSE  FALSE FALSE  FALSE            FALSE
## [212,] FALSE  FALSE FALSE  FALSE            FALSE
## [213,] FALSE  FALSE FALSE  FALSE            FALSE
## [214,] FALSE  FALSE FALSE  FALSE            FALSE
## [215,] FALSE  FALSE FALSE  FALSE            FALSE
## [216,] FALSE  FALSE FALSE  FALSE            FALSE
## [217,] FALSE  FALSE FALSE  FALSE            FALSE
## [218,] FALSE  FALSE FALSE  FALSE            FALSE
## [219,] FALSE  FALSE FALSE  FALSE            FALSE
## [220,] FALSE  FALSE FALSE  FALSE            FALSE
## [221,] FALSE  FALSE FALSE  FALSE            FALSE
## [222,] FALSE  FALSE FALSE  FALSE            FALSE
## [223,] FALSE  FALSE FALSE  FALSE            FALSE
## [224,] FALSE  FALSE FALSE  FALSE            FALSE
## [225,] FALSE  FALSE FALSE  FALSE            FALSE
## [226,] FALSE  FALSE FALSE  FALSE            FALSE
## [227,] FALSE  FALSE FALSE  FALSE            FALSE
## [228,] FALSE  FALSE FALSE  FALSE            FALSE
## [229,] FALSE  FALSE FALSE  FALSE            FALSE
## [230,] FALSE  FALSE FALSE  FALSE            FALSE
## [231,] FALSE  FALSE FALSE  FALSE            FALSE
## [232,] FALSE  FALSE FALSE  FALSE            FALSE
## [233,] FALSE  FALSE FALSE  FALSE            FALSE
## [234,] FALSE  FALSE FALSE  FALSE            FALSE
## [235,] FALSE  FALSE FALSE  FALSE            FALSE
## [236,] FALSE  FALSE FALSE  FALSE            FALSE
## [237,] FALSE  FALSE FALSE  FALSE            FALSE
## [238,] FALSE  FALSE FALSE  FALSE            FALSE
## [239,] FALSE  FALSE FALSE  FALSE            FALSE
## [240,] FALSE  FALSE FALSE  FALSE            FALSE
## [241,] FALSE  FALSE FALSE  FALSE            FALSE
## [242,] FALSE  FALSE FALSE  FALSE            FALSE
## [243,] FALSE  FALSE FALSE  FALSE            FALSE
## [244,] FALSE  FALSE FALSE  FALSE            FALSE
## [245,] FALSE  FALSE FALSE  FALSE            FALSE
## [246,] FALSE  FALSE FALSE  FALSE            FALSE
## [247,] FALSE  FALSE FALSE  FALSE            FALSE
## [248,] FALSE  FALSE FALSE  FALSE            FALSE
## [249,] FALSE  FALSE FALSE  FALSE            FALSE
## [250,] FALSE  FALSE FALSE  FALSE            FALSE
## [251,] FALSE  FALSE FALSE  FALSE            FALSE
## [252,] FALSE  FALSE FALSE  FALSE            FALSE
## [253,] FALSE  FALSE FALSE  FALSE            FALSE
## [254,] FALSE  FALSE FALSE  FALSE            FALSE
## [255,] FALSE  FALSE FALSE  FALSE            FALSE
## [256,] FALSE  FALSE FALSE  FALSE            FALSE
## [257,] FALSE  FALSE FALSE  FALSE            FALSE
## [258,] FALSE  FALSE FALSE  FALSE            FALSE
## [259,] FALSE  FALSE FALSE  FALSE            FALSE
## [260,] FALSE  FALSE FALSE  FALSE            FALSE
## [261,] FALSE  FALSE FALSE  FALSE            FALSE
## [262,] FALSE  FALSE FALSE  FALSE            FALSE
## [263,] FALSE  FALSE FALSE  FALSE            FALSE
## [264,] FALSE  FALSE FALSE  FALSE            FALSE
## [265,] FALSE  FALSE FALSE  FALSE            FALSE
## [266,] FALSE  FALSE FALSE  FALSE            FALSE
## [267,] FALSE  FALSE FALSE  FALSE            FALSE
## [268,] FALSE  FALSE FALSE  FALSE            FALSE
## [269,] FALSE  FALSE FALSE  FALSE            FALSE
## [270,] FALSE  FALSE FALSE  FALSE            FALSE
## [271,] FALSE  FALSE FALSE  FALSE            FALSE
\end{verbatim}

\begin{verbatim}
## integer(0)
\end{verbatim}

\includegraphics{paper_1_supplement_files/figure-latex/coded speaking time-1.pdf}

\hypertarget{eyetracking-data-1}{%
\subsubsection{Eyetracking Data}\label{eyetracking-data-1}}

The Tobii Pro Lab 2 software was used to analyze the teachers' visual attetion during each mini-lesson. The software allows for non-screen based recordings of a participants' attention while moving in real-world settings. The recordings of the glasses contain both HD-video from the subjects' perspective as well as the respective gaze data mapped onto the video. In order to map multiple recordings to AOIs, we first imported the eye-tracking recordings into the Tobii Pro Analyzer software. Second, we created dynamic Areas of Interest (AOI) manually to plot the gaze data. Once the AOIs are created, the gaze recordings of multiple recordings can be mapped and analyzed in aggregated form. Tobii Pro does not allow to do AOI based analyses within Pro Lab. So we exported a tsv. file to do further analyses in the software R.

\hypertarget{gaze-relational-index-gri}{%
\paragraph{Gaze relational index (GRI)}\label{gaze-relational-index-gri}}

The GRI is a measure of visual expertise in information processing. This metric is calculated as the ratio of mean fixation duration to fixation count. The GRI is higher for novices than for experts. (Gegenfurtner et al. (2020))

\begin{verbatim}
## 'data.frame':    80 obs. of  15 variables:
##  $ ID                                        : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Recording                                 : int  33 33 33 33 33 33 33 33 33 33 ...
##  $ Label                                     : chr  "Aperol_pilot_01_04_novice_C_glasses" "Aperol_pilot_01_04_novice_C_glasses" "Aperol_pilot_01_04_novice_C_glasses" "Aperol_pilot_01_04_novice_C_glasses" ...
##  $ Group                                     : chr  "novice" "novice" "novice" "novice" ...
##  $ PersonID                                  : chr  "C" "C" "C" "C" ...
##  $ Session                                   : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ Unit                                      : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ Type.of.disruption                        : chr  "chatting with neighbor" "yelling" "asking a question" "walking around" ...
##  $ Total.duration.of.fixation.in.AOI..sec.   : num  5.89 9.5 5.74 6.62 0.92 ...
##  $ Total.duration.of.fixation.in.AOI..msec.  : num  5889 9500 5745 6617 920 ...
##  $ Average.duration.of.fixation.in.AOI..sec. : num  0.28 0.73 0.96 0.33 0.31 0.67 0.36 0.81 0.53 1.13 ...
##  $ Average.duration.of.fixation.in.AOI..msec.: num  280 731 957 331 307 ...
##  $ Number.of.fixations.in.AOI                : int  21 13 6 20 3 17 12 8 8 15 ...
##  $ Total.Time.of.Interest.Duration..sec.     : num  724 724 724 724 724 ...
##  $ Total.Time.of.Interest.Duration..msec.    : num  723922 723922 723922 723922 723922 ...
\end{verbatim}

\begin{table}[h]

\begin{center}
\begin{threeparttable}

\caption{\label{tab:GRItable}Number and Duration (in msec) of Fixations}

\small{

\begin{tabular}{llllllll}
\toprule
PersonID & \multicolumn{1}{c}{Group} & \multicolumn{1}{c}{Fixation Number} & \multicolumn{1}{c}{Fixation Duration} & \multicolumn{1}{c}{Average Duration Fixation} & \multicolumn{1}{c}{SE Duration Fixation} & \multicolumn{1}{c}{TOI} & \multicolumn{1}{c}{GRI}\\
\midrule
A & expert & 14.00 & 6,980.81 & 498.63 & 1,034.60 & 838,025.59 & 35.62\\
A & expert & 7.00 & 4,674.45 & 667.78 & 1,034.60 & 838,025.59 & 95.40\\
A & expert & 15.00 & 4,217.56 & 281.17 & 1,034.60 & 838,025.59 & 18.74\\
A & expert & 26.00 & 4,740.12 & 182.31 & 1,034.60 & 838,025.59 & 7.01\\
A & expert & 26.00 & 7,275.66 & 279.83 & 1,034.60 & 838,025.59 & 10.76\\
A & expert & 22.00 & 9,295.02 & 422.50 & 1,034.60 & 838,025.59 & 19.20\\
A & expert & 19.00 & 7,155.72 & 376.62 & 1,034.60 & 838,025.59 & 19.82\\
A & expert & 30.00 & 11,273.40 & 375.78 & 1,034.60 & 838,025.59 & 12.53\\
A & expert & 25.00 & 5,387.20 & 215.49 & 1,034.60 & 838,025.59 & 8.62\\
A & expert & 13.00 & 14,400.23 & 1,107.71 & 1,034.60 & 838,025.59 & 85.21\\
A & novice & 9.00 & 1,499.18 & 166.58 & 1,144.21 & 729,762.37 & 18.51\\
A & novice & 21.00 & 8,307.13 & 395.58 & 1,144.21 & 729,762.37 & 18.84\\
A & novice & 1.00 & 159.91 & 159.91 & 1,144.21 & 729,762.37 & 159.91\\
A & novice & 5.00 & 341.45 & 68.29 & 1,144.21 & 729,762.37 & 13.66\\
A & novice & 38.00 & 7,131.35 & 187.67 & 1,144.21 & 729,762.37 & 4.94\\
A & novice & 18.00 & 2,154.55 & 119.70 & 1,144.21 & 729,762.37 & 6.65\\
A & novice & 8.00 & 1,363.86 & 170.48 & 1,144.21 & 729,762.37 & 21.31\\
A & novice & 20.00 & 3,437.99 & 170.48 & 1,144.21 & 729,762.37 & 8.52\\
A & novice & 9.00 & 1,174.07 & 130.45 & 1,144.21 & 729,762.37 & 14.49\\
A & novice & 28.00 & 10,183.38 & 363.69 & 1,144.21 & 729,762.37 & 12.99\\
B & novice & 16.00 & 11,435.47 & 714.72 & 1,235.77 & 744,444.49 & 44.67\\
B & novice & 8.00 & 5,403.07 & 675.38 & 1,235.77 & 744,444.49 & 84.42\\
B & novice & 9.00 & 7,182.87 & 798.10 & 1,235.77 & 744,444.49 & 88.68\\
B & novice & 21.00 & 19,342.95 & 921.09 & 1,235.77 & 744,444.49 & 43.86\\
B & novice & 21.00 & 20,068.02 & 955.62 & 1,235.77 & 744,444.49 & 45.51\\
B & novice & 6.00 & 8,090.41 & 1,348.40 & 1,235.77 & 744,444.49 & 224.73\\
B & novice & 10.00 & 5,353.29 & 535.33 & 1,235.77 & 744,444.49 & 53.53\\
B & novice & 14.00 & 10,168.97 & 726.36 & 1,235.77 & 744,444.49 & 51.88\\
B & novice & 36.00 & 19,857.95 & 551.61 & 1,235.77 & 744,444.49 & 15.32\\
B & novice & 18.00 & 10,375.46 & 576.42 & 1,235.77 & 744,444.49 & 32.02\\
B & novice & 11.00 & 3,859.60 & 350.87 & 1,235.77 & 730,565.01 & 31.90\\
B & novice & 9.00 & 5,537.67 & 615.30 & 1,235.77 & 730,565.01 & 68.37\\
B & novice & 7.00 & 4,593.66 & 656.24 & 1,235.77 & 730,565.01 & 93.75\\
B & novice & 10.00 & 7,031.68 & 703.17 & 1,235.77 & 730,565.01 & 70.32\\
B & novice & 9.00 & 3,477.94 & 386.44 & 1,235.77 & 730,565.01 & 42.94\\
B & novice & 18.00 & 8,328.93 & 462.72 & 1,235.77 & 730,565.01 & 25.71\\
B & novice & 9.00 & 3,269.13 & 363.24 & 1,235.77 & 730,565.01 & 40.36\\
B & novice & 25.00 & 5,227.18 & 209.09 & 1,235.77 & 730,565.01 & 8.36\\
B & novice & 4.00 & 2,418.56 & 604.64 & 1,235.77 & 730,565.01 & 151.16\\
B & novice & 13.00 & 12,524.66 & 963.44 & 1,235.77 & 730,565.01 & 74.11\\
C & novice & 21.00 & 5,889.47 & 280.45 & 963.62 & 723,922.27 & 13.35\\
C & novice & 13.00 & 9,500.22 & 730.79 & 963.62 & 723,922.27 & 56.21\\
C & novice & 6.00 & 5,744.89 & 957.48 & 963.62 & 723,922.27 & 159.58\\
C & novice & 20.00 & 6,616.62 & 330.83 & 963.62 & 723,922.27 & 16.54\\
C & novice & 3.00 & 919.80 & 306.60 & 963.62 & 723,922.27 & 102.20\\
C & novice & 17.00 & 11,339.68 & 667.04 & 963.62 & 723,922.27 & 39.24\\
C & novice & 12.00 & 4,280.81 & 356.73 & 963.62 & 723,922.27 & 29.73\\
C & novice & 8.00 & 6,456.24 & 807.03 & 963.62 & 723,922.27 & 100.88\\
C & novice & 8.00 & 4,277.53 & 534.69 & 963.62 & 723,922.27 & 66.84\\
C & novice & 15.00 & 16,953.86 & 1,130.26 & 963.62 & 723,922.27 & 75.35\\
C & novice & 10.00 & 7,867.69 & 786.77 & 963.62 & 737,604.07 & 78.68\\
C & novice & 15.00 & 13,418.17 & 894.55 & 963.62 & 737,604.07 & 59.64\\
C & novice & 5.00 & 4,717.15 & 943.43 & 963.62 & 737,604.07 & 188.69\\
C & novice & 11.00 & 5,617.35 & 510.67 & 963.62 & 737,604.07 & 46.42\\
C & novice & 8.00 & 3,698.21 & 462.28 & 963.62 & 737,604.07 & 57.78\\
C & novice & 25.00 & 9,921.86 & 396.88 & 963.62 & 737,604.07 & 15.88\\
C & novice & 10.00 & 2,648.60 & 264.86 & 963.62 & 737,604.07 & 26.49\\
C & novice & 13.00 & 4,392.88 & 337.91 & 963.62 & 737,604.07 & 25.99\\
C & novice & 27.00 & 9,751.48 & 361.17 & 963.62 & 737,604.07 & 13.38\\
C & novice & 19.00 & 15,753.36 & 829.12 & 963.62 & 737,604.07 & 43.64\\
D & expert & 6.00 & 4,235.49 & 705.91 & 1,971.55 & 781,978.04 & 117.65\\
D & expert & 7.00 & 2,978.23 & 425.46 & 1,971.55 & 781,978.04 & 60.78\\
D & expert & 3.00 & 1,443.21 & 481.07 & 1,971.55 & 781,978.04 & 160.36\\
D & expert & 35.00 & 20,863.43 & 596.10 & 1,971.55 & 781,978.04 & 17.03\\
D & expert & 10.00 & 5,475.55 & 547.56 & 1,971.55 & 781,978.04 & 54.76\\
D & expert & 6.00 & 3,468.42 & 578.07 & 1,971.55 & 781,978.04 & 96.35\\
D & expert & 7.00 & 4,622.55 & 660.36 & 1,971.55 & 781,978.04 & 94.34\\
D & expert & 10.00 & 4,976.97 & 497.70 & 1,971.55 & 781,978.04 & 49.77\\
D & expert & 15.00 & 7,805.47 & 520.36 & 1,971.55 & 781,978.04 & 34.69\\
D & expert & 10.00 & 15,834.07 & 1,583.41 & 1,971.55 & 781,978.04 & 158.34\\
D & novice & 5.00 & 18,600.29 & 1,959.01 & 2,291.16 & 747,729.29 & 391.80\\
D & novice & 9.00 & 469.84 & 1,953.66 & 2,291.16 & 747,729.29 & 217.07\\
D & novice & 3.00 & 8,822.52 & 179.90 & 2,291.16 & 747,729.29 & 59.97\\
D & novice & 9.00 & 3,957.60 & 582.63 & 2,291.16 & 747,729.29 & 64.74\\
D & novice & 7.00 & 219.85 & 2,318.57 & 2,291.16 & 747,729.29 & 331.22\\
D & novice & 1.00 & 16,229.98 & 219.85 & 2,291.16 & 747,729.29 & 219.85\\
D & novice & 2.00 & 5,243.62 & 1,978.80 & 2,291.16 & 747,729.29 & 989.40\\
D & novice & 12.00 & 539.70 & 735.21 & 2,291.16 & 747,729.29 & 61.27\\
D & novice & 2.00 & 17,582.95 & 234.92 & 2,291.16 & 747,729.29 & 117.46\\
D & novice & 14.00 & 9,795.03 & 1,328.59 & 2,291.16 & 747,729.29 & 94.90\\
\bottomrule
\end{tabular}

}

\end{threeparttable}
\end{center}

\end{table}

\hypertarget{data-analysis}{%
\subsection{Data analysis}\label{data-analysis}}

We used R {[}Version 4.0.3; R Core Team (2019){]} and the R-packages \emph{\}dplyr} {[}@\}R-dplyr{]}, \emph{forcats} {[}Version 0.5.0; Wickham (2020a){]}, \emph{ggplot2} {[}Version 3.3.2; Wickham (2016){]}, \emph{papaja} {[}Version 0.1.0.9997; Aust and Barth (2020){]}, \emph{papayar} (Muschelli, 2016), \emph{purrr} {[}Version 0.3.4; Henry and Wickham (2020){]}, \emph{readr} {[}Version 1.4.0; Wickham, Hester, and Francois (2018){]}, \emph{stringr} {[}Version 1.4.0; Wickham (2019){]}, \emph{tibble} {[}Version 3.0.4; Müller and Wickham (2021){]}, \emph{tidyr} {[}Version 1.1.2; Wickham (2020b){]}, and \emph{tidyverse} {[}Version 1.3.0; Wickham et al. (2019){]} for all our analyses.

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\hypertarget{questionnaire-data-2}{%
\subsubsection{Questionnaire Data}\label{questionnaire-data-2}}

\hypertarget{behavioral-data-2}{%
\subsubsection{Behavioral Data}\label{behavioral-data-2}}

\hypertarget{eyetracking-data-2}{%
\subsubsection{Eyetracking Data}\label{eyetracking-data-2}}

\hypertarget{results}{%
\section{Results}\label{results}}

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\hypertarget{questionnaire-data-3}{%
\subsubsection{Questionnaire Data}\label{questionnaire-data-3}}

\hypertarget{behavioral-data-3}{%
\subsubsection{Behavioral Data}\label{behavioral-data-3}}

\hypertarget{eyetracking-data-3}{%
\subsubsection{Eyetracking Data}\label{eyetracking-data-3}}

\hypertarget{discussion}{%
\section{Discussion}\label{discussion}}

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\newpage

\hypertarget{references}{%
\section{References}\label{references}}

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\hypertarget{ref-R-papaja}{}%
Aust, F., \& Barth, M. (2020). \emph{{papaja}: {Create} {APA} manuscripts with {R Markdown}}. Retrieved from \url{https://github.com/crsh/papaja}

\leavevmode\hypertarget{ref-barnes2004significance}{}%
Barnes, D. (2004). The significance of teachers' frames for teaching. In \emph{Teachers and teaching} (pp. 16--38). Routledge.

\leavevmode\hypertarget{ref-barth2017professionelle}{}%
Barth, V. L. (2017). \emph{Professionelle wahrnehmung von störungen im unterricht}. Springer.

\leavevmode\hypertarget{ref-berliner2001learning}{}%
Berliner, D. C. (2001). Learning about and learning from expert teachers. \emph{International Journal of Educational Research}, \emph{35}(5), 463--482.

\leavevmode\hypertarget{ref-bogert2016visualperception}{}%
Bogert, N. J. van den. (2016). \emph{On teachers' visual perception and interpretation of classroom events using eye tracking and collaborative tagging methodologies}. Technische Universiteit Eindhoven.

\leavevmode\hypertarget{ref-brophy1986classroom}{}%
Brophy, J. (1986). Classroom management techniques. \emph{Education and Urban Society}, \emph{18}(2), 182--194.

\leavevmode\hypertarget{ref-cortina2015low}{}%
Cortina, K. S., Miller, K. F., McKenzie, R., \& Epstein, A. (2015). Where low and high inference data converge: Validation of CLASS assessment of mathematics instruction using mobile eye tracking with expert and novice teachers. \emph{International Journal of Science and Mathematics Education}, \emph{13}(2), 389--403.

\leavevmode\hypertarget{ref-gegenfurtner2020gaze}{}%
Gegenfurtner, A., Boucheix, J.-M., Gruber, H., Hauser, F., Lehtinen, E., \& Lowe, R. K. (2020). The gaze relational index as a measure of visual expertise. \emph{Journal of Expertise. East Lansing, Michigan: Michigan State University, 2020, Vol. 3, Iss. 1}.

\leavevmode\hypertarget{ref-helmke2014unterrichtsdiagnostik}{}%
Helmke, A., Helmke, T., Lenske, G., Pham, G., Praetorius, A.-K., Schrader, F.-W., \& AdeThurow, M. (2014). Unterrichtsdiagnostik mit EMU. \emph{Aus-Und Fortbildung Der Lehrkr{ä}fte in Hinblick Auf Verbesserung Der Diagnosef{ä}higkeit, Umgang Mit Heterogenit{ä}t Und Individuelle F{ö}rderung}, 149--163.

\leavevmode\hypertarget{ref-R-purrr}{}%
Henry, L., \& Wickham, H. (2020). \emph{Purrr: Functional programming tools}. Retrieved from \url{https://CRAN.R-project.org/package=purrr}

\leavevmode\hypertarget{ref-jarodzka2010eyes}{}%
Jarodzka, H., Scheiter, K., Gerjets, P., \& Van Gog, T. (2010). In the eyes of the beholder: How experts and novices interpret dynamic stimuli. \emph{Learning and Instruction}, \emph{20}(2), 146--154.

\leavevmode\hypertarget{ref-kiel2013trainingsbuch}{}%
Kiel, E., Frey, A., Weiß, S., \& Weiss, S. (2013). \emph{Trainingsbuch klassenf{ü}hrung} (Vol. 3992). UTB.

\leavevmode\hypertarget{ref-kounin2006techniken}{}%
Kounin, J. S. (2006). \emph{Techniken der klassenf{ü}hrung}. Waxmann Verlag.

\leavevmode\hypertarget{ref-kuckartz2019analyzing}{}%
Kuckartz, U., \& Rädiker, S. (2019). \emph{Analyzing qualitative data with MAXQDA}. Springer.

\leavevmode\hypertarget{ref-lachner2016makes}{}%
Lachner, A., Jarodzka, H., \& Nückles, M. (2016). What makes an expert teacher? Investigating teachers' professional vision and discourse abilities. \emph{Instructional Science}, \emph{44}(3), 197--203.

\leavevmode\hypertarget{ref-marzano2007art}{}%
Marzano, R. J. (2007). \emph{The art and science of teaching: A comprehensive framework for effective instruction}. Ascd.

\leavevmode\hypertarget{ref-messner2000berufliche}{}%
Messner, H., \& Reusser, K. (2000). Die berufliche entwicklung von lehrpersonen als lebenslanger prozess. \emph{Beitr{ä}ge Zur Lehrerinnen-Und Lehrerbildung}, \emph{18}(2), 157--171.

\leavevmode\hypertarget{ref-R-papayar}{}%
Muschelli, J. (2016). \emph{Papayar: View medical research images using the papaya JavaScript library}. Retrieved from \url{https://CRAN.R-project.org/package=papayar}

\leavevmode\hypertarget{ref-R-tibble}{}%
Müller, K., \& Wickham, H. (2021). \emph{Tibble: Simple data frames}. Retrieved from \url{https://CRAN.R-project.org/package=tibble}

\leavevmode\hypertarget{ref-nolting2012storungen}{}%
Nolting, H.-P. (2012). \emph{St{ö}rungen in der schulklasse}. Beltz.

\leavevmode\hypertarget{ref-pouta2020student}{}%
Pouta, M., Lehtinen, E., \& Palonen, T. (2020). Student teachers' and experienced teachers' professional vision of students' understanding of the rational number concept.

\leavevmode\hypertarget{ref-R-base}{}%
R Core Team. (2019). \emph{R: A language and environment for statistical computing}. Vienna, Austria: R Foundation for Statistical Computing. Retrieved from \url{https://www.R-project.org/}

\leavevmode\hypertarget{ref-stuermer2017eye}{}%
Stuermer, K., Seidel, T., Mueller, K., Häusler, J., \& Cortina, K. S. (2017). What is in the eye of preservice teachers while instructing? An eye-tracking study about attention processes in different teaching situations. \emph{Zeitschrift f{ü}r Erziehungswissenschaft}, \emph{20}(1), 75--92.

\leavevmode\hypertarget{ref-R-ggplot2}{}%
Wickham, H. (2016). \emph{ggplot2: Elegant graphics for data analysis}. Springer-Verlag New York. Retrieved from \url{https://ggplot2.tidyverse.org}

\leavevmode\hypertarget{ref-R-stringr}{}%
Wickham, H. (2019). \emph{Stringr: Simple, consistent wrappers for common string operations}. Retrieved from \url{https://CRAN.R-project.org/package=stringr}

\leavevmode\hypertarget{ref-R-forcats}{}%
Wickham, H. (2020a). \emph{Forcats: Tools for working with categorical variables (factors)}. Retrieved from \url{https://CRAN.R-project.org/package=forcats}

\leavevmode\hypertarget{ref-R-tidyr}{}%
Wickham, H. (2020b). \emph{Tidyr: Tidy messy data}. Retrieved from \url{https://CRAN.R-project.org/package=tidyr}

\leavevmode\hypertarget{ref-R-tidyverse}{}%
Wickham, H., Averick, M., Bryan, J., Chang, W., McGowan, L. D., François, R., \ldots{} Yutani, H. (2019). Welcome to the {tidyverse}. \emph{Journal of Open Source Software}, \emph{4}(43), 1686. \url{https://doi.org/10.21105/joss.01686}

\leavevmode\hypertarget{ref-R-readr}{}%
Wickham, H., Hester, J., \& Francois, R. (2018). \emph{Readr: Read rectangular text data}. Retrieved from \url{https://CRAN.R-project.org/package=readr}

\leavevmode\hypertarget{ref-wolff2017see}{}%
Wolff, C. E., Jarodzka, H., \& Boshuizen, H. P. (2017). See and tell: Differences between expert and novice teachers' interpretations of problematic classroom management events. \emph{Teaching and Teacher Education}, \emph{66}, 295--308.

\end{CSLReferences}

\endgroup


\end{document}
