---
title: "Fit Bit - First Look"
output: html_notebook
---

# Packages

```{r}
#install.packages("needs")
#1

library(needs)

needs(tidyverse,
      lubridate,
      viridis,
      grid,
      gridExtra,
      cowplot,
      readxl,
      ARTofR)
```


# Data 

```{r, message=FALSE, include=FALSE, error=FALSE}
part <- read_xlsx(path = "Data/Heart Rate.xlsx")

#...............................................................................
#                                                                              .
#  Enter the missing cases in Heart Rate table below.                                       .
#                                                                              .
#...............................................................................

part <- filter(part,
              `ID participant` != 108 # |
              #`ID participant` != | etc.
              )

part <- part$`ID participant`

for (i in part) {
  nam <- paste("m", i, sep = "")
  assign(x = nam, 
         value = read_csv(file = paste("Data/", i, "_m.csv", sep = ""
                                       )
                          )
         ) 
}

for (i in part) {
  nam <- paste("a", i, sep = "")
  assign(x = nam, 
         value = read_csv(file = paste("Data/", i, "_a.csv", sep = ""
                                       )
                          )
         ) 
}

for (i in part) {
  nam <- paste("p", i, sep = "")
  assign(x = nam, 
         value = read_csv(file = paste("Data/", i, "_p.csv", sep = ""
                                       )
                          )
         ) 
}

# m101 <- read_csv(file = "Data/101_m.csv")
# m102 <- read_csv(file = "Data/102_m.csv")
# m103 <- read_csv(file = "Data/103_m.csv")
# m104 <- read_csv(file = "Data/104_m.csv")
# m105 <- read_csv(file = "Data/105_m.csv")
# 
# p101 <- read_csv(file = "Data/101_p.csv")
# p102 <- read_csv(file = "Data/102_p.csv")
# p103 <- read_csv(file = "Data/103_p.csv")
# p104 <- read_csv(file = "Data/104_p.csv")
# p105 <- read_csv(file = "Data/105_p.csv")
# 
# a101 <- read_csv(file = "Data/101_a.csv")
# a102 <- read_csv(file = "Data/102_a.csv")
# a103 <- read_csv(file = "Data/103_a.csv")
# a104 <- read_csv(file = "Data/104_a.csv")
# a105 <- read_csv(file = "Data/105_a.csv")

# z <- ls()

```

# Change Time to seconds

```{r}
for (i in part) {
  nam <- paste0("m", i)
  value <- get(nam)$Time - min(get(nam)$Time)
  `Heart Rate` <- get(nam)$`Heart Rate`
  df <- tibble(Time = as.numeric(value),
               `Heart Rate` = `Heart Rate`,
               ID = i
               )
  assign(paste0("m", i), df)
}

for (i in part) {
  nam <- paste0("a", i)
  value <- get(nam)$Time - min(get(nam)$Time)
  `Heart Rate` <- get(nam)$`Heart Rate`
  df <- tibble(Time = as.numeric(value),
               `Heart Rate` = `Heart Rate`,
               ID = i
               )
  assign(paste0("a", i), df)
}

for (i in part) {
  nam <- paste0("p", i)
  value <- get(nam)$Time - min(get(nam)$Time)
  `Heart Rate` <- get(nam)$`Heart Rate`
  df <- tibble(Time = as.numeric(value),
               `Heart Rate` = `Heart Rate`,
               ID = i
               )
  assign(paste0("p", i), df)
}

# m101$Time <- m101$Time - min(m101$Time)
# m102$Time <- m102$Time - min(m102$Time)
# m103$Time <- m103$Time - min(m103$Time)
# m104$Time <- m104$Time - min(m104$Time)
# m105$Time <- m105$Time - min(m105$Time)
# 
# p101$Time <- p101$Time - min(p101$Time)
# p102$Time <- p102$Time - min(p102$Time)
# p103$Time <- p103$Time - min(p103$Time)
# p104$Time <- p104$Time - min(p104$Time)
# p105$Time <- p105$Time - min(p105$Time)
# 
# a101$Time <- a101$Time - min(a101$Time)
# a102$Time <- a102$Time - min(a102$Time)
# a103$Time <- a103$Time - min(a103$Time)
# a104$Time <- a104$Time - min(a104$Time)
# a105$Time <- a105$Time - min(a105$Time)
```

# ID

```{r}
# m101$ID <- 101
# p101$ID <- 101
# a101$ID <- 101
# 
# m102$ID <- 102
# p102$ID <- 102
# a102$ID <- 102
# 
# m103$ID <- 103
# p103$ID <- 103
# a103$ID <- 103
# 
# m104$ID <- 104
# p104$ID <- 104
# a104$ID <- 104
# 
# m105$ID <- 105
# p105$ID <- 105
# a105$ID <- 105

```

# Join Data Frames

```{r}
rm(part)
rm(nam)
rm(`Heart Rate`)
rm(i)
rm(value)
rm(df)

df_m <- 
  mget(ls(pattern = "m")) %>%
  bind_rows()

df_p <- 
  mget(ls(pattern = "p")) %>%
  bind_rows()

df_a <- 
  mget(ls(pattern = "a")) %>%
  bind_rows()

#rm(list = as.character(z))
#rm(z)
```

# Plots

## Last Data Adjustments

```{r}
df_a$Type <- "Post"
df_m$Type <- "Main"
df_p$Type <- "Pre"

df_all <- bind_rows(list(df_a,df_p, df_m))

df_all <- df_all %>%
  mutate(Type = factor(Type,
                       levels = c("Pre","Main","Post")),
         ID = as_factor(ID)
         )

#df_all$Time <- scale(df_all$Time)

df_aggr <- df_all %>%
  group_by(Type, ID) %>%
  summarise(mean = mean(`Heart Rate`))


 df_all$status <- if_else(as.numeric(as.character(df_all$ID)) < 200,
                          "novice",
                          "advanced")

 df_all_min <- df_all %>%
 group_by(ID) %>%
   summarise(min = max(Time))

```

## Flow

```{r}
plot_flow <-
ggplot(data = filter(df_all),
       mapping = aes(x = as.numeric(Time),
                     y = `Heart Rate`
                     )
       ) +
  geom_path(mapping = aes(color = as_factor(ID)),
            size = 0.4,
            alpha = 0.6) +
  # stat_smooth(geom = "line",
  #             mapping = aes(color = as.factor(ID)),
  #             method = "loess",
  #             se = FALSE,
  #             linetype = 2) +
  xlim(0,min(df_all_min$min)) +
  scale_color_viridis_d(option = "A",
                        end = 0.8) +
  labs(x = "Time (in Seconds)",
       y = "Heart Rate\n(in Beats per Minute)") +
  theme_minimal() +
  theme(text = element_text(family = "serif"),
        legend.position = "none",
        strip.text = element_text(size = 16)) +
  facet_grid(cols = vars(Type),
             scales = "free_x")

plot_flow_leg <-
ggplot(data = df_all,
       mapping = aes(x = Time,
                     y = `Heart Rate`
                     )
       ) +
 # geom_line(mapping = aes(color = ID)) +
  geom_smooth(mapping = aes(color = as_factor(ID)),
              method = "loess") +
  scale_color_viridis_d(option = "A",
                        end = 0.8) +
  labs(x = "Time (in Seconds)",
       y = "Heart Rate\n(in Beats per Minute)") +
  theme_minimal() +
  theme(text = element_text(family = "serif"),
        legend.title = element_blank()) +
  facet_grid(cols = vars(Type))

legend <- cowplot::get_legend(plot_flow_leg)

plot_loess <-
ggplot(data = filter(df_all),
       mapping = aes(x = as.numeric(Time),
                     y = `Heart Rate`
                     )
       ) +
  # geom_path(mapping = aes(color = as_factor(ID)),
  #           size = 0.4,
  #           alpha = 0.4) +
  stat_smooth(geom = "line",
              mapping = aes(color = as.factor(ID)),
              method = "loess",
              se = FALSE) +
  xlim(0,min(df_all_min$min)) +
  scale_color_viridis_d(option = "A",
                        end = 0.8) +
  labs(x = "Time (in Seconds)",
       y = "Heart Rate\n(in Beats per Minute)") +
  theme_minimal() +
  facet_grid(cols = vars(Type),
             scales = "free_x",
             ) +
  theme(text = element_text(family = "serif"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.text.x = element_blank()
        )
```

## Boxplots

```{r}
plot_box <- 
ggplot(data = df_aggr,
       mapping = aes(x = Type,
                     y = mean,
                     color = as_factor(ID)
                     )
       ) +
  geom_boxplot(color = "darkgrey",
               fill = "grey",
               alpha = 0.6) +
  geom_line(mapping = aes(group = as_factor(ID))) +
  geom_point(size = 2) +
  labs(x = "",
       y = "Average Heart Rate\n(in Beats per Minute)") +
  scale_color_viridis_d(option = "A",
                       end = 0.8) +
  theme_minimal() +
  theme(text = element_text(family = "serif"),
        strip.text = element_blank(),
        legend.position = "none",
        axis.text.x = element_blank()
        ) +
  aes(fill = Type)

plot_box
```

## Combine

```{r}
lo_mat <- rbind(c(1,1,1,1,1,1,NA),
                c(2,2,2,2,2,2,4),
                c(3,3,3,3,3,3,NA))

plot_fitbit <- 
grid.arrange(grobs = list(plot_flow, plot_loess, plot_box, legend),
             layout_matrix = lo_mat)

ggsave(plot = plot_fitbit,
       file = "Plots/fitbit.pdf",
       height = 16,
       width = 20,
       units = "cm"
       )
```

# Steps

## Data
```{r}
df_steps <- read_xlsx(path = "Data/Heart Rate.xlsx")
```

```{r}
df_steps <- df_steps %>%
  transmute(ID = as.numeric(as.character(df_steps$`ID participant`)),
            Steps = Diff
            )

df_steps$type <- ifelse(df_steps$ID < 200, 
                        "Novice",
                        "Advanced"
                        )
```

```{r}
df_aggr_main <- df_aggr %>% mutate(ID = as.numeric(as.character(ID)),
                                      ) %>%
  ungroup() %>%
  filter(Type == "Main") %>%
  select(ID, mean)

#df_aggr_main$ID <- as.numeric(df_aggr_main$ID)

df_steps <- full_join(x = df_aggr_main,
                      y = df_steps,
                      key = ID)
```
```{r}
df_steps$mean <- scale(df_steps$mean)
df_steps$Steps <- scale(df_steps$Steps)

plot_scatter <-
ggplot(data = df_steps,
       mapping = aes(x = Steps,
                     y = mean)
       ) +
    geom_smooth(mapping = aes(color = type),
              method = "lm",
              se = F) +
  geom_point(mapping = aes(shape = type),
             alpha = 0.6,
             size = 2.5) +
  scale_color_viridis_d(option = "A",
                       end = 0.8,
                       begin = 0.3
                       ) +
  labs(x = "Steps\n(z-standardized)",
       y = "Mean Heart Rate\n(z-standardized)"
       ) +
  theme_minimal() +
  theme(text = element_text(family = "serif"),
        legend.title = element_blank(),
        )
 
ggsave(plot = plot_scatter,
       filename = "Plots/scatter.pdf",
       height = 5,
       width = 7,
       units = "in")

```

