---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Writing - Original Draft Preparation
      - Writing - Review & Editing
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"
    role:
      - Writing - Review & Editing

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : bookdown::word_document2 #papaja::apa6_pdf
---

```{r setup, include = FALSE}

library("papaja")
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```


# Packages

```{r}
#install.packages("needs")

# suppress "summarize" info. 
# if this line is ommitted, each table using the summarize function will be accompanied with a warning from the console
options(dplyr.summarise.inform = FALSE)

library(needs)

needs(tidyverse,
      lubridate,
      viridis,
      grid,
      gridExtra,
      cowplot,
      readxl,
      ARTofR)
```


# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

```{r demographicstable, echo = FALSE}

# prepare data (selected from questionnaire data)
demo.data <- read_excel ("./data/data_empschul_labor_lehrperson.xlsx") 

# select relevant columns
demo.data <- demo.data %>% select(LI02_01_1,
                                  LI03_01,
                                  LI04_01,
                                  LI06_05)


# rename columns
demo.data <- rename(demo.data, c("Group" = "LI06_05",
                                  "Gender" = "LI02_01_1",
                                  "Age" = "LI03_01",
                                  "Teaching Experience" = "LI04_01"))

# define expert and novice with ifelse function
demo.data$Group = ifelse(demo.data$Group < 200, "Novice","Expert")

# changing gender female 2 = 0 
demo.data$Gender = ifelse(demo.data$Gender == 2, "0","1")

# changing character into numeric
demo.data$Gender <- as.numeric(demo.data$Gender)

# create a basic table (tibble) using tidyverse functions
demo.table <- demo.data %>%
  group_by(Group) %>%
  summarise(N=n(),
            "Male" = sum(Gender),
            "M Age" = round(mean(Age), 2),
            "Min Age" = min(Age),
            "Max Age" = max(Age),
            "SD Age" = round(sd(Age), 2),
            "M Exp." = round(mean(`Teaching Experience`), 2),
            "Min Exp." = min(`Teaching Experience`),
            "Max Exp." = max(`Teaching Experience`),
            "SD Exp." = round(sd(`Teaching Experience`), 2),
           )

# format and insert table in manuscript
apa_table(
  demo.table,
  caption = "Demographic Information and Teaching Experience",
  # note = "Write Note here", 
  escape = TRUE, # if TRUE special Latex characters are escaped; if this is turned to F captions cannot be rendered. I don't know why...
  placement = "h", # position of table in page:  exact location (h), at the top (t), bottom (b)
  font_size = "small" # options are tiny, scriptsize, footnotesize, small, normalsize (default), large, Large, LARGE, huge, Huge
  )

```

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
