---
title: "Graphics GRI"
output: html_notebook
---

Packages

```{r}
library(needs)
needs(tidyverse,
      gridExtra,
      viridis,
      ggthemes)
```


```{r}
# prepare data (selected from questionnaire data)
df_gri <- read_delim("data/Aperol_pilot_glasses_raw_metrics_all_TOI.tsv", 
                     delim = "\t", escape_double = FALSE, trim_ws = TRUE)


# converting integer to numeric
df_gri <- mutate(.data = df_gri,
                 Duration_of_interval = as.numeric(Duration_of_interval),
                 Total_duration_of_whole_fixations = as.numeric(Total_duration_of_whole_fixations),
                 Number_of_whole_fixations = as.numeric(Number_of_whole_fixations),
                 Average_duration_of_whole_fixations = as.numeric(Average_duration_of_whole_fixations)
                 )

# calculate the GRI 
# create a basic table (tibble) using tidyverse functions
df_gri <- df_gri %>%
  group_by(TOI) %>%
  summarise("ID" = Participant,
            "Group" = Variable1,
            "DurTOI" = Duration_of_interval,
            "M Dur Fix" = mean(Total_duration_of_whole_fixations),
            "Number Fix" = Number_of_whole_fixations,
            "TimeTOI Dur" = Duration_of_interval/mean(Total_duration_of_whole_fixations),
            "OldGRI" = mean(Total_duration_of_whole_fixations)/Number_of_whole_fixations,
            "NewGRI" = (Duration_of_interval/mean(Total_duration_of_whole_fixations))/Number_of_whole_fixations,
            "NewGRI_scale" = scale((Duration_of_interval/mean(Total_duration_of_whole_fixations))/Number_of_whole_fixations))

df_gri$Group <- as_factor(df_gri$Group)

```

List of Variables:

- TOI: Time of Interest; Type of Event
- ID: ID of Person
- Group: Novice or Expert
- DurTOI: Frames of TOI
- M Dur Fix: Mean time of Fixations per Type of Event
- Number Fix: Number of Fixations during Event
- TimeTOI Dur:
- OldGRI
- NewGRI

# Compare all Variables

```{r}
df_gri_comp <- select(df_gri,
                      !ID)

df_gri_comp <- pivot_longer(data = df_gri,
                            c("DurTOI","M Dur Fix","Number Fix",
                              "TimeTOI Dur","OldGRI","NewGRI","NewGRI_scale"))

df_gri_comp$name <- factor(df_gri_comp$name,
                           levels = c("DurTOI","M Dur Fix","Number Fix",
                                      "TimeTOI Dur","OldGRI","NewGRI",
                                      "NewGRI_scale"),
                           labels = c("Duration TOI","Total dur. of whole fixations (mean)",
                                      "Number of whole fixations","TimeTOI Dur","GRI","Adjusted GRI","Adjusted GRI (scaled)")
                           )
                  

ggplot(data = filter(df_gri_comp,
                     TOI != "Calibration phase"),
       mapping = aes(x = Group,
                     y = value
                     )
       ) +
  geom_boxplot(mapping = aes(fill = Group)) +
  geom_point(size = 2, 
             alpha = 0.4,
             position = position_jitter(seed = 1, 
                                        width = 0.1
                                        )
             ) +
  scale_fill_brewer(palette = "RdBu") +
  theme_clean() +
  facet_wrap(vars(name), 
             scale = "free")
```

# Novice vs. Expert (GRI)
Erste Idee:

```{r}
ggplot(data = filter(df_gri_comp,
                     name == "Old GRI" |
                     name == "Adjusted GRI" |
                     name == "Adjusted GRI (scaled)"),
       mapping = aes(x = Group,
                     y = value
                     )
       ) +
  geom_boxplot(mapping = aes(fill = Group)) +
  geom_point(size = 2, 
             alpha = 0.4,
             position = position_jitter(seed = 1, 
                                        width = 0.1
                                        )
             ) +
  scale_fill_brewer(palette = "RdBu") +
  theme_clean() +
  facet_wrap(vars(name),
             scales = "free")
```

# Comparison GRI over TOIs

```{r}
ggplot(data = filter(df_gri_comp,
                     name == "Old GRI" |
                     name == "Adjusted GRI" |
                     name == "Adjusted GRI (scaled)"),
       mapping = aes(x = TOI,
                     y = value
                     )
       ) +
  geom_boxplot(mapping = aes(fill = Group)) +
  geom_point(size = 2, 
             alpha = 0.4,
             position = position_jitter(seed = 1, 
                                        width = 0.1
                                        )
             ) +
  scale_fill_brewer(palette = "RdBu") +
  theme_clean() +
  facet_wrap(vars(name),
             scales = "free")
```



```{r}

for (i in unique(df_gri$TOI)) {

    assign(paste("plot_", i, sep = ""), 
           ggplot(data = filter(df_gri,
                                TOI == i
                                ),
                  mapping = aes(x = factor(0),
                                y = NewGRI
                                )
                  ) +
             geom_boxplot(mapping = aes(fill = Group)
                          ) +
             labs(x = "",
                  y = "Adjusted GRI",
                  title = i)
           )
    
  }

plot_asking <- `plot_Asking question`
plot_chatting <- `plot_Chatting with neighbour`
plot_clicking <- `plot_Clicking pen`
plot_drawing <- `plot_Drawing on paper`
plot_drumming <- `plot_Drumming hands`
plot_looking <- `plot_Looking at phone`
plot_head <- `plot_Putting head on table`
plot_yelling <- plot_Yelling

df_gri$NewGRI_scale <- scale(df_gri$NewGRI)


grid.arrange(plot_asking,
             plot_chatting,
             plot_clicking,
             plot_drawing,
             plot_drumming,
             plot_looking,
             plot_head,
             plot_yelling,
             heights = c(1,1),
             widths = c(1,1,1,1),
             layout_matrix = matrix(1:8,
                                    nrow = 2,
                                    ncol = 4,
                                    byrow = TRUE
                                    ),
             name = "Difference between Novice and Expert"
             )

```






```{r}
ggplot(data = df_gri,
       mapping = aes(x = factor(0),
                     y = NewGRI_scale
                     )
       ) +
  geom_boxplot(mapping = aes(fill = Group)
               ) +
  labs(x = "",
       y = "Adjusted GRI (standardized)"
      ) + 
  facet_wrap(vars(factor(TOI))) +
  scale_fill_brewer(palette = "RdBu")
  
```

